### ISSUE TITLE
BUG: Cashier and banker won't work

### ISSUE THREAD

**Issue by haithem2459** [Lightman314/LightmansCurrency#102]
### Minecraft Version

1.19.2

### Forge Version

43.1.1

### Lightman's Currency Version

2.0.0.4

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

 I tried a solo world as well with just that mod alone to test it, but the villagers don't convert to those two jobs.

### To Reproduce

Placed a bunch of registers and atm's

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrency/files/9945230/latest.log)

**Comment by Lightman314** [comment]
It would appear that you are correct. For some odd reason they don't properly gain their jobs in 1.19 (works fine in 1.18 though).

**Comment by Lightman314** [comment]
Update: Figured out why it wasn't working (apparently the point of interest needs a tag now...). Should be fixed in the next update.

**Comment by Lightman314** [comment]
Fixed in v2.0.0.5
