### ISSUE TITLE
BUG: Energy trader does not work

### ISSUE THREAD

**Issue by killeroid356** [Lightman314/LightmansCurrency#103]
### Minecraft Version

1.18.2

### Forge Version

40.1.84

### Lightman's Currency Version

2.0.0.4

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

LC Tech 0.1.0.1

### Describe the bug

Energy traders will not select energy trades, despite clicking on them, i cannot auto buy or sell energy, even when i have more than enough room / energy to buy / sell

### To Reproduce

place down energy trader

select energy merchant

attempt to select relevant trade

nothing happens

main page says no trade linked

### Screenshots/Logs/Crash Reports

![image](https://user-images.githubusercontent.com/34097198/200196885-7a183292-441f-4c30-9710-0efddfce8267.png)
![image](https://user-images.githubusercontent.com/34097198/200196892-4d3ed42a-8922-4e2a-ad63-b30338a49ad1.png)

**Comment by Lightman314** [comment]
Please report issues with LC Tech on the [LC Tech issue page](https://github.com/Lightman314/LCTech/issues). This page is for issues with Lightman's Currency alone, not any of its addon mods.
