### ISSUE TITLE
BUG: 1.18.2 - Latest - Crashes on Server Start-up

### ISSUE THREAD

**Issue by Phweeeee** [Lightman314/LightmansCurrency#105]
### Minecraft Version

1.18.2

### Forge Version

40.1.85

### Lightman's Currency Version

2.0.0.5a

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

When trying to start up a dedicated server, the game crashes with the crash report below.

### To Reproduce

Not too sure, it may be a mod conflict, but this happens when launching a dedicated server with the mod. 

### Screenshots/Logs/Crash Reports

https://paste.gg/p/anonymous/e0a63c87c34647cfb7d496c78cbba9b1

**Comment by Lightman314** [comment]
Fixed in v2.0.0.5b
