### ISSUE TITLE
Feature Request: {add a function of individual transaction}

### ISSUE THREAD

**Issue by Guda-nemo** [Lightman314/LightmansCurrency#106]
Hi your mod is really impressive and I really love it but I found that there's a lack of funcitons for individual transactions. So my idea is that could u add a item allows players to trade with each other by face to face or online? It's too comlex for some of players to set a shop for selling items and This makes the economy of my server have been developing badly.

**Comment by Lightman314** [comment]
I do like the idea of being able to make a trade request with other players. Will probably make it a command (at least the requesting part, the actual trading will definitely have its own UI). 

Unfortunately, I'm fairly busy working on a Fabric port atm, so I can't promise this will be added any time soon.

**Comment by Lightman314** [comment]
Just updating this to let you know that this feature is WIP and should be included in the next update (whenever that may happen).

**Comment by Guda-nemo** [comment]
thanks very much!!! By the way, do you need a chinese lang file? I'v translated all texts for the current verison, you can send me a file of new texts that added in the next update so that I can help you to make a completed chinese lang file.

**Comment by Lightman314** [comment]
If you could provide a up-to-date translation, I'd appreciate it.

Here's the latest English language file (renamed into a txt file because apparently github doesn't support attaching *.json files in comments):
[en_us.json.txt](https://github.com/Lightman314/LightmansCurrency/files/10202835/en_us.json.txt)

**Comment by Guda-nemo** [comment]
[zh_cn.json.txt](https://github.com/Lightman314/LightmansCurrency/files/10205610/zh_cn.json.txt)
I've finished, hope this can help you.

**Comment by Guda-nemo** [comment]
wait, will the next update be 1.18 version?

**Comment by Lightman314** [comment]
Added in v2.0.1.0.
