### ISSUE TITLE
BUG: Machines do not recognize their owners

### ISSUE THREAD

**Issue by mcmardigangamer** [Lightman314/LightmansCurrency#107]
### Minecraft Version

1.18.2

### Forge Version

40.1.85

### Lightman's Currency Version

1.2.0.4

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

Hello, I have detected a problem in the mod and I need help to fix it.
I have a server where users have created stores with the mod's machines (display caser or item trader server), and now they can't access their settings. Even from the Terminal it does not appear who owns the machine. This has happened as a result of changing my hosting server. I have dumped all the files to the new host but the fact is that now the machines do not recognize their owners. I would be grateful if you could help me to solve the problem since it would be a very big nuisance to have to give new machines to the users to reconfigure their stores. Thanks in advance.

### To Reproduce

1º I make a backup copy of the world hosted on my server
2º New hosting contract
3º I restore backup copy of the world in my new hosting
4º I enter the world and when I right click on one of the machines (display caser or item trader server), it does not recognize me as the owner so I cannot access the machine configuration

### Screenshots/Logs/Crash Reports

The problem detected is only applicable to the mod in question and does not affect the rest of the operation of the server

**Comment by Lightman314** [comment]
I'm afraid I would be unable to help you understand why this happened without having access to the world data, or at least the `lightmanscurrency_trader_data.dat` file (found in *world*/data). If you could create a new trader, call it "Test Trader" or something, and then provide that data file, I may be able to look into why it doesn't recognise you.

That said, the only reason it shouldn't is if your UUID somehow changed in the server transition (which shouldn't be possible as it's linked to your Mojang account, unless you had online-mode turned off in the server.properties).

**Comment by mcmardigangamer** [comment]
Hello again, indeed in the server.PROPERTIES I have destabilized the online_mode since we play all with Tlauncher. But I also do not understand why the machines do not recognize each one as owner of those we have placed since, the data overturned to the new hosting are the same as the previous server. As an idea, it would be good that an item, English key or something, so that a server administrator can access the machine configuration and can assign it again who is its owner.
I also attach the data file to see if you can take a look and indicate where the error is.
![2022-12-03_17 57 47](https://user-images.githubusercontent.com/119747526/205453240-250a4c0b-a6aa-49f3-a201-6d9cb56c67a0.jpg)
[lightmanscurrency_trading_office.zip](https://github.com/Lightman314/LightmansCurrency/files/10146987/lightmanscurrency_trading_office.zip)
![2022-12-03_18 19 06](https://user-images.githubusercontent.com/119747526/205453494-c45c65e5-a379-4bfc-835f-9664f53551d1.jpg)

**Comment by Lightman314** [comment]
The machines do not recognize you as the owner, because your UUID changed during the server transfer (which is a side-effect of having `online-mode=false` in the server.properties.

Because of this I do not support any "Issues" that arise when a server is in offline mode, so either have your friends actually buy the game and use your official Mojang account, or use LC Admin Mode to transfer the ownership back to their rightful owners manually.

![image](https://user-images.githubusercontent.com/4554273/205458627-3702ebbc-0cee-4071-bce5-3ebe7824f1f4.png)

**Comment by mcmardigangamer** [comment]
Thank you very much for your answer. It has been very helpful. Could you please tell me how to use the LC administration mode to transfer the machines back to their owners. Thank you very much beforehand for your help.

**Comment by Lightman314** [comment]
https://github.com/Lightman314/LightmansCurrency/wiki/Trading-Machines#ownership-tab
https://github.com/Lightman314/LightmansCurrency/wiki/Administrator-Features#moderation
