### ISSUE TITLE
BUG: Server did not create a server file, only created the common file.

### ISSUE THREAD

**Issue by StrwbryMoon** [Lightman314/LightmansCurrency#109]
### Minecraft Version

1.19.2

### Forge Version

43.1.55

### Lightman's Currency Version

2.0.1.0

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

I have a ATM8 modpack with a few additional mods. 

### Describe the bug

Mod works 100% fine, but did not create a server config file for the server, so I cannot disable crafting & smelting of coins.

### To Reproduce

Placed currency mod into the mods folder, booted server, config files there minus the server file.

### Screenshots/Logs/Crash Reports

[https://gyazo.com/fe3d200e2ba02423f7e0d487414661c3](url)

**Comment by Lightman314** [comment]
The server config file is generated in the `world/serverconfig` folder, not the `config` folder that the common/client config files go.
