### ISSUE TITLE
1.18 fabric update?

### ISSUE THREAD

**Issue by lostopkk** [Lightman314/LightmansCurrency#11]

**Comment by Lightman314** [comment]
I have no plans on ever porting this mod to fabric, sorry. You are far from the first person to ask though, and I don't mind another developer porting my mod to fabric but I'm still putting together a set of rules I want them to follow.

**Comment by mortifia** [comment]
it's sad, I also switched to fabric and I liked this mod

**Comment by Lightman314** [comment]
There is now actually a fabric port of this mod. You can find it [here](https://www.curseforge.com/minecraft/mc-mods/lightmans-currency-fabric).

**Comment by mortifia** [comment]
thank you for this information, it's nice to have answered.

just currently there is very little of mod transtorted in 1.19-x

**Comment by lostopkk** [comment]
> There is now actually a fabric port of this mod. You can find it [here](https://www.curseforge.com/minecraft/mc-mods/lightmans-currency-fabric).

Thank you for the port!!! i'm very happy for this!

**Comment by lostopkk** [comment]
> There is now actually a fabric port of this mod. You can find it [here](https://www.curseforge.com/minecraft/mc-mods/lightmans-currency-fabric).

sorry to create another comment for this but i always wanted this mod to put in my modpack, could i put it with your permission?

https://github.com/lostopkk/Decoration-Perfomance
