### ISSUE TITLE
Feature Request: Credit Card and Bizum (player to player payment)

### ISSUE THREAD

**Issue by albertosaurio65** [Lightman314/LightmansCurrency#110]
Credit Card:
-------------
A card linked to the account to avoid having to put coins all the time

For security, the card codes could be simulated so that another player does not use your card, and for online purchases through the server you could ask for the 3-digit code and the password

The card could be contactless and you only have to right-click on a new dataphone type block to pay for what you entered, customizing in your account from which certain price to ask for a password

I see this more inspired by stores than by vending machines, you can link the dataphone with the cashier or put manual the price

This is a dataphone: If you introduce the credit card, you must put the password, and if you use the contactless, you need to put the password if the payment is x>limit

![image](https://user-images.githubusercontent.com/70109413/212560907-6d8bb6d0-d9b2-4ab9-899e-b292d7941c1b.png)

PD: exist vending machine with credit card payment ( card payment in vending machines could be an upgrade, if activated the dataphone appears on the model ):  
![image](https://user-images.githubusercontent.com/70109413/212561108-eed28a76-0e0a-4a17-82a8-607a0c0006fc.png)

Bizum ( Spanish app):
------------------------
A system to pay money online to players with a new item or app, is like bank income but more easy with the telephone number, in this case another special method or idk

![image](https://user-images.githubusercontent.com/70109413/212561123-348cec34-8ee3-4d4a-8741-d5fff259f51b.png)

You can solicit o give

![image](https://user-images.githubusercontent.com/70109413/212561228-f76f0ba1-6e23-49be-bbc7-4ff1ab416bce.png)

Maybe a new item like mobile phone or laptops to chat or do online shopping, if you create the mobile phone, implement the contactless mode like a credit card

![image](https://user-images.githubusercontent.com/70109413/212561324-c0d7a4e5-cf5a-46d3-81e6-5f11fd60d187.png)

**Comment by Lightman314** [comment]
> A card linked to the account to avoid having to put coins all the time

You already don't need to put coins in the slots all of the time. Unless you're manually exchanging coins at an ATM, nearly every money interaction in the mod will automatically collect and pay coins to your equipped wallet (including picking up coins from the ground if you have a gold wallet or better).

Also, I don't see how any of the solutions you suggest would even be feasible to add into a pixelated Minecraft environment without making the purchasing process even more complicated than it already is.

**Comment by albertosaurio65** [comment]
I haven't played with this mod for a long time so I'm not aware of the issue, I literally remembered the mod today when I saw a ping from the discord, and then I remembered another mod that had credit cards and I suggested it, nothing more
