### ISSUE TITLE
BUG: Persistant trader Ignores Trade Rules

### ISSUE THREAD

**Issue by ZEROX7** [Lightman314/LightmansCurrency#111]
### Minecraft Version

1.19.2

### Forge Version

43.2.2

### Lightman's Currency Version

2.0.1.0

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

Persistant trader has 14 trades each with following rules 1. item free and then 24h buy limit
but wehn i get my first batch i can still get more items for free it seems the player tracking is bugged there

### To Reproduce

persistant trader with 1 trade wit hthe following rules 1.free and a player trade limit wich forgets it 24h later

### Screenshots/Logs/Crash Reports

![image](https://user-images.githubusercontent.com/12628051/212738192-b4e7a00f-b3c0-49bc-b627-7e5e5a190618.png)
![image](https://user-images.githubusercontent.com/12628051/212738232-4dc7ff38-b61c-431a-979c-ef6aff551fe3.png)
![image](https://user-images.githubusercontent.com/12628051/212738248-d5a2646f-6da1-4002-a6fb-1cef9aa802aa.png)

**Comment by ZEROX7** [comment]
Update it seems its just a display issue if i click on a trade i dont get any items

**Comment by Lightman314** [comment]
There must be some sort of server -> client sync issue with the Trade Rules then. I'll look into it and make sure it gets fixed before the next update.

**Comment by Lightman314** [comment]
Fixed in v2.0.1.2. I'm not sure *when* I plan to back-port LC back to 1.19.2, but unless any major bugs come to light, this will likely be the version I port.

**Comment by Dzoted** [comment]
Создайте пожалуйста видео обзор, как создавать постоянный трейдер. У меня ни как не получается.

**Comment by Lightman314** [comment]
> Создайте пожалуйста видео обзор, как создавать постоянный трейдер. У меня ни как не получается.

First off, this comment has nothing to do with this issue (the issue being that the trade rules didn't get synced properly on persistent traders), so why you're posting this here I have no clue.

Second, I already have a [wiki page](https://github.com/Lightman314/LightmansCurrency/wiki/Persistent-Traders#creating-a-persistent-trader-in-game) detailing exactly how this is done (both in-game and by manually editing the file). If you need additional help past that join my discord server (link is at the bottom of the mod description on curseforge), and ask for help there, as Github is to be used for reporting bugs/issues, or making a feature request, **not** for asking for help on how to use a feature.

**Comment by Dzoted** [comment]
Простите что вас тревожу, просто я все перепробовал. Я когда настраивал постоянный трейдер и нажимал кнопку создать постоянный трейдер, после я прописывал команду /lcreload. Но почему-то после перезапуска мира, ни чего не сохранилось. Прошу помогите. Я просто не нашёл ссылку куда обратиться. А мне мож сильно понравился. И больше я так делать не буду. Спасибо большое, заранее

**Comment by Dzoted** [comment]
@ZEROX7 можно с тобой связаться через дискорд на счёт мода Lightmans currency и постоянных трейдеров. Просто не как не получается создать постоянный трейдер. Пожалуйста напиши мне как с тобой лучше связаться и обговорить.

**Comment by ZEROX7** [comment]
> @ZEROX7 можно с тобой связаться через дискорд на счёт мода Lightmans currency и постоянных трейдеров. Просто не как не получается создать постоянный трейдер. Пожалуйста напиши мне как с тобой лучше связаться и обговорить.

sry dont speak that languages

**Comment by Dzoted** [comment]
> > @ZEROX7можно связаться через дискорд на счёт моды Валюта Lightmans и заинтересованные трейдеры. Просто не как не получается создать постоянный трейдер. Пожалуйста, напиши мне как с тобой лучше связаться и обговорить.
> 
> извините, не говорите на этих языках

Please, you can write how to contact you and discuss the issue of fashion Lightmans currency. I can't figure out a regular trader.

**Comment by Darknessdz1** [comment]
> > @ZEROX7можно связаться через дискорд на счёт моды Валюта Lightmans и заинтересованные трейдеры. Просто не как не получается создать постоянный трейдер. Пожалуйста, напиши мне как с тобой лучше связаться и обговорить.
> 
> извините, не говорите на этих языках

@ZEROX7 How do I contact you. I would like to discuss persistent traders. I can't create them. I would like to ask how to do this correctly. Can I contact you or any other social network via discord?

**Comment by Lightman314** [comment]
> Fixed in v2.0.1.2. I'm not sure _when_ I plan to back-port LC back to 1.19.2, but unless any major bugs come to light, this will likely be the version I port.

LC v2.1.0.0 has now been back-ported to 1.19.2, so this issue is now fixed across all relevant versions.
