### ISSUE TITLE
BUG: Server Enviroment Crash on Startup

### ISSUE THREAD

**Issue by Zelioth** [Lightman314/LightmansCurrency#112]
### Minecraft Version

1.19.3

### Forge Version

44.1.5

### Lightman's Currency Version

2.0.1.1

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

Startup when loading Lightmans Currency it appears to crash. The crash report gives a server watchdog crash but the server hasn't even started yet. the log shows the crash report but the actual crash report does not .

### To Reproduce

place mods in server files.
run server
crash, poof, boom, owe.

### Screenshots/Logs/Crash Reports

Crash 
https://gist.github.com/Zelioth/c644ebc1ca3ba95bdd581f63133a58a4

Log 
https://gist.github.com/Zelioth/7aff656457ea060a259d06478f7098f3

Report pulled from last lines of log
https://gist.github.com/Zelioth/f8d1bc4417f2e2a7ad3143d16f10d8fb

**Comment by Lightman314** [comment]
Found the issue, and will be fixed in the next update, which should be coming out later today.

**Comment by Lightman314** [comment]
Fixed in v2.0.1.2
