### ISSUE TITLE
BUG: Vending Machines attempt to trade twice

### ISSUE THREAD

**Issue by hedonicknight** [Lightman314/LightmansCurrency#113]
### Minecraft Version

1.19.3

### Forge Version

44.1.0

### Lightman's Currency Version

2.0.1.2a

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

When trading with a Large Vending Machine, trades are executed twice. Attempting to trade with only enough materials/currency for 1 trade results in 1 trade successfully occurring. The issue only occurs if you have enough of the requested items to execute the transaction twice.

The obvious workaround is to throw/deposit extra currency or materials before trading, but this is clearly not the expected behavior for the player.

### To Reproduce

1. Craft/Place a Large Vending Machine.
2. Set up any type of trade.
3. Have enough materials in storage inside the machine and in inventory to execute two transactions.
4. Execute one transaction.
5. The transaction is executed twice.

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrency/files/10475600/latest.log)

**Comment by Lightman314** [comment]
Fixed in v2.0.1.2b. Thank you for reporting :)
