### ISSUE TITLE
BUG:  Network Traders T3 and above are uncraftable

### ISSUE THREAD

**Issue by hedonicknight** [Lightman314/LightmansCurrency#114]
### Minecraft Version

1.19.3

### Forge Version

44.1.0

### Lightman's Currency Version

2.0.1.2b

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

Despite existing in /item commands, network traders T3 and above do not craft from their documented recipe.

### To Reproduce

1. Craft a Small (T1) Network Trading Server.
2. Craft a Medium (T2) Network Trading Server.
3. Layout the documented materials to craft a Large (T3) Trading Server.

The Large Trading Server is not crafted.

### Screenshots/Logs/Crash Reports

![2023-01-25_09 24 50](https://user-images.githubusercontent.com/43123531/214588971-fb5559f6-1d1f-4130-81fe-cd0290e45e1e.png)

**Comment by hedonicknight** [comment]
Should note, I did manually give myself a T3 to attempt to craft a T4, and the same issue applies.

**Comment by Lightman314** [comment]
The recipe you are using is not the correct recipe. It should just be a chest above and an iron ingot below, (and the trader in the center), and nothing else. If you need recipe help please install JEI as it does now have a 1.19.3 version, as the wiki is a touch out of date in regards to recipes.
