### ISSUE TITLE
BUG: Conversion of Emerald trades to coins

### ISSUE THREAD

**Issue by Zelioth** [Lightman314/LightmansCurrency#115]
### Minecraft Version

1.19.2

### Forge Version

43.2.4

### Lightman's Currency Version

2.0.1.0

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

Crash upon entry of new world geneartion

### To Reproduce

install mods that make secondary villagers
use those mods
yes

### Screenshots/Logs/Crash Reports

https://gist.github.com/Zelioth/1f225ffb7c86be9f511b66a18e232bfc

**Comment by Lightman314** [comment]
As I mentioned on the discord, this is a mod conflict between Pneumaticraft and Blue Skies, and has nothing to do with my mod. I would instead report this issue to either Pneumaticraft or Blue Skies. I would recommend reporting it to Pneumaticraft, as the ItemListing.getOffer villager/entity input is required to be non-null by vanilla Minecraft, so intentionally leaving it null is bound to cause errors/mod conflicts.
