### ISSUE TITLE
BUG: Client crash when searching in trader

### ISSUE THREAD

**Issue by HollishKid** [Lightman314/LightmansCurrency#117]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Lightman's Currency Version

1.16.4-1.0.5.6a

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

See the crash log here: https://pastebin.com/9rhB4ZWQ

### Describe the bug

The attempting to do a search in the trader, the client instantly crashes.
This may be related to #116?

### To Reproduce

Attempt a search in the trader.

### Screenshots/Logs/Crash Reports

https://pastebin.com/9rhB4ZWQ

**Comment by Lightman314** [comment]
I can 100% promise you that this has nothing to do with the issue you mentioned/tagged.
I'll see if I can get this fixed, but it will take a lot of work just to get my 1.16 version of this mod editable again so it will be quite a while until this is fixed unfortunately (you were warned that the 1.16 version is no longer supported in the curseforge description)

**Comment by Lightman314** [comment]
Fixed in the latest v2.1.0.0 backport.
