### ISSUE TITLE
BUG: crash to main menu when putting coin bag/wallet in curious slot

### ISSUE THREAD

**Issue by Xplodin** [Lightman314/LightmansCurrency#118]
### Minecraft Version

1.16.5

### Forge Version

36.2.39

### Lightman's Currency Version

2.1.0.0

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

curious, tbh not much else I would think.

### Describe the bug

kicks to main menu and possibly corrupt playerdata

### To Reproduce

install beanpack: rebeanified
make a money pouch/wallet (gold) 
try to put it in curious and get disconnected from server

sorry if this isnt enough info its just what happened. Server made an apparent crash report but never produced one so I copied relevant lines from console. I also dont have much time as I got a flight to catch in 6 hours

### Screenshots/Logs/Crash Reports

net.minecraft.crash.ReportedException: Ticking player
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:467) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207) ~[?:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226) ~[?:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.func_217855_b(Ljava/lang/String;)Z
	at io.github.lightman314.lightmanscurrency.common.money.util.CoinValueParser.TryParseCoin(CoinValueParser.java:82) ~[lightmanscurrency:1.16.5-2.1.0.0]
	at io.github.lightman314.lightmanscurrency.common.money.util.CoinValueParser.parse(CoinValueParser.java:40) ~[lightmanscurrency:1.16.5-2.1.0.0]
	at io.github.lightman314.lightmanscurrency.common.money.util.CoinValueParser.ParseConfigString(CoinValueParser.java:23) ~[lightmanscurrency:1.16.5-2.1.0.0]
	at io.github.lightman314.lightmanscurrency.util.config.CoinValueConfig.get(CoinValueConfig.java:40) ~[lightmanscurrency:1.16.5-2.1.0.0]
	at io.github.lightman314.lightmanscurrency.common.enchantments.MoneyMendingEnchantment.getRepairCost(MoneyMendingEnchantment.java:48) ~[lightmanscurrency:1.16.5-2.1.0.0]
	at io.github.lightman314.lightmanscurrency.common.enchantments.MoneyMendingEnchantment.runEntityTick(MoneyMendingEnchantment.java:60) ~[lightmanscurrency:1.16.5-2.1.0.0]
	at io.github.lightman314.lightmanscurrency.common.enchantments.EnchantmentEvents.onEntityTick(EnchantmentEvents.java:34) ~[lightmanscurrency:1.16.5-2.1.0.0]
	at net.minecraftforge.eventbus.ASMEventHandler_1109_EnchantmentEvents_onEntityTick_LivingUpdateEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:326) ~[forge:?]
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114) ~[?:?]
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223) ~[?:?]
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404) ~[?:?]
	... 9 more
[13Mar2023 05:50:48.958] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: net.minecraft.util.ResourceLocation.func_217855_b(Ljava/lang/String;)Z
	Index: 25
	Listeners:
		0: HIGHEST
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@1e27da31
		2: ASM: wayoftime.bloodmagic.util.handler.event.GenericHandler@5074696f onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		3: NORMAL
		4: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@778792ec
		5: ASM: insane96mcp.progressivebosses.module.wither.feature.MiscFeature@5ea9ac50 onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		6: ASM: insane96mcp.progressivebosses.module.wither.feature.HealthFeature@5c5cd8aa onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		7: ASM: insane96mcp.progressivebosses.module.wither.feature.MinionFeature@3ad11159 update(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		8: ASM: insane96mcp.progressivebosses.module.wither.feature.AttackFeature@33a00852 onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		9: ASM: insane96mcp.progressivebosses.module.dragon.feature.HealthFeature@704e199c onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		10: ASM: insane96mcp.progressivebosses.module.dragon.feature.RewardFeature@714e7587 onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		11: ASM: insane96mcp.progressivebosses.module.dragon.feature.MinionFeature@3eb2e3a7 update(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		12: ASM: insane96mcp.progressivebosses.module.dragon.feature.LarvaFeature@7b766e93 update(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		13: ASM: insane96mcp.progressivebosses.module.elderguardian.feature.HealthFeature@7a5ad3a4 onUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		14: ASM: insane96mcp.progressivebosses.module.elderguardian.feature.MinionFeature@5a9fdc36 update(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		15: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@4eedd16
		16: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@8b52288
		17: ASM: com.rolfmao.upgradednetherite.handlers.EventHandler@22931755 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		18: ASM: com.rolfmao.upgradednetherite.handlers.ArmorEventHandler@6a590450 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		19: ASM: com.rolfmao.upgradednetherite.handlers.ToolEventHandler@680ec955 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		20: ASM: com.rolfmao.upgradednetherite.handlers.HorseArmorEventHandler@28c68a40 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		21: ASM: everlastingabilities onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		22: ASM: class com.brandon3055.brandonscore.handlers.BCEventHandler livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		23: ASM: class net.mrscauthd.boss_tools.events.Events onLivingEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		24: ASM: class io.github.lightman314.lightmanscurrency.common.EventHandler entityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		25: ASM: class io.github.lightman314.lightmanscurrency.common.enchantments.EnchantmentEvents onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		26: ASM: class slimeknights.tconstruct.tools.logic.ToolEvents livingWalk(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		27: ASM: com.github.alexthe666.citadel.server.CitadelEvents@552a483e onEntityUpdateDebug(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		28: ASM: com.github.alexthe666.citadel.server.CitadelEvents@552a483e onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		29: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@41e813b1 onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		30: ASM: class net.silentchaos512.gems.chaos.ChaosHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		31: ASM: class owmii.losttrinkets.handler.TargetHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		32: ASM: class owmii.losttrinkets.handler.EventHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		33: ASM: class owmii.losttrinkets.handler.DataManager update(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		34: ASM: class com.github.alexthe666.rats.server.events.CommonEvents onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		35: ASM: class twilightforest.TFEventListener livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		36: ASM: class com.brandon3055.draconicevolution.handlers.ModularArmorEventHandler livingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		37: ASM: com.integral.enigmaticlegacy.handlers.EnigmaticEventHandler@6590f9d4 onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		38: ASM: class com.minecraftabnormals.abnormals_core.core.events.CompatEvents onUpdateEntity(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		39: ASM: class cofh.ensorcellation.event.ShieldEnchEvents handleLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		40: ASM: class cofh.ensorcellation.event.HorseEnchEvents handleLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		41: ASM: class cofh.ensorcellation.event.CommonEvents handleLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		42: ASM: class com.minecraftabnormals.savageandravage.core.other.SREvents livingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		43: ASM: com.sr2610.creeperconfetti.ConfettiHandler@67b03b1d creeperExplodeEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		44: ASM: com.lothrazar.cyclic.enchant.EnchantLaunch@156c1a02 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		45: ASM: stepsword.mahoutsukai.handlers.ServerHandler@4e489cb1 livingEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		46: ASM: class com.minecraftabnormals.upgrade_aquatic.core.events.EntityEvents onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		47: ASM: class com.minecraftabnormals.atmospheric.core.other.AtmosphericEvents livingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		48: ASM: boss_tools_giselle_addon.common.content.proof.SpaceOxygenProofUtils@13046886 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		49: ASM: boss_tools_giselle_addon.common.content.proof.SpaceGravityProofUtils@291eb4dc onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		50: ASM: boss_tools_giselle_addon.common.content.proof.SpaceFireProofUtils@22352c80 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		51: ASM: boss_tools_giselle_addon.common.content.proof.VenusAcidProofUtils@2c3d0433 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		52: ASM: class com.stal111.forbidden_arcanus.event.LivingUpdateListener onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		53: ASM: class com.simibubi.create.events.CommonEvents onUpdateLivingEntity(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		54: ASM: class com.simibubi.create.content.curiosities.tools.ExtendoGripItem holdingExtendoGripIncreasesRange(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		55: ASM: class com.simibubi.create.content.curiosities.armor.DivingHelmetItem breatheUnderwater(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		56: ASM: class com.simibubi.create.content.curiosities.armor.DivingBootsItem accellerateDescentUnderwater(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		57: ASM: class com.ma.events.CommonEventHandler onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		58: ASM: class com.ma.capabilities.MACapabilityForgeEventHandlers onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		59: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@28e387fd
		60: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@63b870ff
		61: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@114c07f3
		62: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@304cc630
		63: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@42463ab
		64: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@243bd458
		65: ASM: com.lothrazar.cyclic.enchant.EnchantGrowth@592ac86e onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		66: ASM: com.lothrazar.cyclic.enchant.EnchantMagnet@662e7cc onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		67: ASM: com.lothrazar.cyclic.enchant.EnchantQuickdraw@59a6855f onPlayerUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		68: ASM: com.lothrazar.cyclic.enchant.EnchantReach@4a8d1a23 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		69: ASM: com.lothrazar.cyclic.enchant.EnchantStep@1bb3b072 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		70: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@55393cb3
		71: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@3920d62
		72: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@248c1f80
		73: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@5eef865d
		74: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@42aff597
		75: ASM: vazkii.quark.content.tweaks.module.DragonScalesModule@334d9f9c onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		76: ASM: vazkii.quark.content.tweaks.module.PoisonPotatoUsageModule@104724b7 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		77: ASM: vazkii.quark.content.world.module.BiotiteModule@24b3c52b onEntityTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		78: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@514509bd
		79: ASM: top.theillusivec4.champions.common.ChampionEventsHandler@4d82d06a onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		80: ASM: tschipp.carryon.common.event.ItemEvents@4d2d62ce dropNonHotbarItems(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		81: ASM: tschipp.carryon.common.event.ItemEntityEvents@429d5c2e onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		82: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@15f17c0a
		83: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@370ecd87
		84: net.minecraftforge.eventbus.EventBus$$Lambda$2612/1232932696@ab085bc
		85: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@669318e1 tick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		86: ASM: flaxbeard.immersivepetroleum.common.CommonEventHandler@59bbea31 test(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		87: ASM: com.blakebr0.mysticalagriculture.handler.AugmentHandler@6a2843c2 onPlayerUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		88: ASM: squeek.appleskin.network.SyncHandler@1ae37306 onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		89: ASM: mekanism.common.lib.radiation.RadiationManager@5118e95c onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		90: ASM: com.lothrazar.cyclic.event.PotionEvents@1e4df6f4 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		91: ASM: com.inventorypets.events.PlayerTickHandler@7f53305d onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		92: ASM: com.inventorypets.events.GravePetHandler@45ff3cb0 gravePetLoadEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		93: ASM: com.inventorypets.events.ItemEntityEvents@18da6294 handleLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		94: ASM: com.lothrazar.cyclic.event.ItemEvents@2f5d234c onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		95: ASM: com.lothrazar.cyclic.event.PlayerAbilityEvents@77430097 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		96: ASM: de.teamlapen.vampirism.entity.ModEntityEventHandler@47713050 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		97: ASM: blusunrize.immersiveengineering.common.EventHandler@57b937f9 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		98: ASM: com.github.alexthe666.iceandfire.event.ServerEvents@56183414 onEntityUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		99: ASM: de.teamlapen.lib.entity.EntityEventHandler@232cc058 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		100: ASM: com.natamus.snowballsfreezemobs.events.SnowEvent@4ea094d0 onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
		101: ASM: mob_grinding_utils.events.ChickenFuseEvent@35ae6304 startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
		102: LOWEST
		103: ASM: class ovh.corail.tombstone.event.EventHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingUpdateEvent;)V
java.lang.NoSuchMethodError: net.minecraft.util.ResourceLocation.func_217855_b(Ljava/lang/String;)Z
	at io.github.lightman314.lightmanscurrency.common.money.util.CoinValueParser.TryParseCoin(CoinValueParser.java:82)
	at io.github.lightman314.lightmanscurrency.common.money.util.CoinValueParser.parse(CoinValueParser.java:40)
	at io.github.lightman314.lightmanscurrency.common.money.util.CoinValueParser.ParseConfigString(CoinValueParser.java:23)
	at io.github.lightman314.lightmanscurrency.util.config.CoinValueConfig.get(CoinValueConfig.java:40)
	at io.github.lightman314.lightmanscurrency.common.enchantments.MoneyMendingEnchantment.getRepairCost(MoneyMendingEnchantment.java:48)
	at io.github.lightman314.lightmanscurrency.common.enchantments.MoneyMendingEnchantment.runEntityTick(MoneyMendingEnchantment.java:60)
	at io.github.lightman314.lightmanscurrency.common.enchantments.EnchantmentEvents.onEntityTick(EnchantmentEvents.java:34)
	at net.minecraftforge.eventbus.ASMEventHandler_1109_EnchantmentEvents_onEntityTick_LivingUpdateEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:326)
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2114)
	at net.minecraft.entity.player.PlayerEntity.func_70071_h_(PlayerEntity.java:223)
	at net.minecraft.entity.player.ServerPlayerEntity.func_71127_g(ServerPlayerEntity.java:404)
	at net.minecraft.network.play.ServerPlayNetHandler.func_73660_a(ServerPlayNetHandler.java:207)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:226)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:134)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:865)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Lightman314** [comment]
Should be fixed in 2.1.0.0a.
