### ISSUE TITLE
Feature Request: {Compatibility with Doggy Talents}

### ISSUE THREAD

**Issue by emanuele246gi** [Lightman314/LightmansCurrency#120]
**Is your feature request related to a problem? Please describe.**
I noticed that in the survival inventory GUI (as you can see in the screenshot below) the Lightsman's Currency slot is overlapped with the dog's inventory.

**Describe the solution you'd like**
-

**Describe alternatives you've considered**
Moving the LC button when both mods are installed to a position where both can coexist, as I already made a post in DT's Github but it doesn't seems to be very active.

**Additional context**
Minecraft 1.18.2
Doggy Talents 2.5.11
Lightman's Currency 2.1.1.0
![image](https://user-images.githubusercontent.com/61762317/229341913-f3314717-2f2b-4b50-8247-9e6f934587d4.png)

**Comment by Lightman314** [comment]
Please use the [Client Config](https://github.com/Lightman314/LightmansCurrency/wiki/Mod-Configuration#client-config) to move the wallet slot out of the way so that the wallet slot and the button do not overlap (just lower the y value by approx 18 pixels).
