### ISSUE TITLE
BUG: Cannot create auction on dedicated server

### ISSUE THREAD

**Issue by MasonGulu** [Lightman314/LightmansCurrency#125]
### Minecraft Version

1.18.2

### Forge Version

40.2.1

### Lightman's Currency Version

2.1.1.1

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

Attempting to create an auction results in the "Create Auction" button greying out, and nothing happening, only thing you can do is close the UI or change tabs, both resulting in your items dropping out. 

There is no related output in the client log.

The server log prints an error anytime a player attempts to create an auction.

`[01:44:27] [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class io/github/lightman314/lightmanscurrency/common/traders/tradedata/client/TradeRenderManager for invalid dist DEDICATED_SERVER`

### To Reproduce

1. Create an auction
2. Sit there and wonder what happened

### Screenshots/Logs/Crash Reports

The only output is in the server log:

`[01:44:27] [Server thread/FATAL] [ne.mi.fm.lo.RuntimeDistCleaner/DISTXFORM]: Attempted to load class io/github/lightman314/lightmanscurrency/common/traders/tradedata/client/TradeRenderManager for invalid dist DEDICATED_SERVER`

UI after clicking create auction
![2023-04-16_21 47 35](https://user-images.githubusercontent.com/70228812/232359058-e9c8ecaa-c143-4c29-ae53-3c8add954151.png)

**Comment by Lightman314** [comment]
Fixed in v2.1.1.1a
