### ISSUE TITLE
BUG: Config doesn't generate default mob & chest loot entries.

### ISSUE THREAD

**Issue by Denis0819** [Lightman314/LightmansCurrency#128]
### Minecraft Version

1.19.4

### Forge Version

45.0.8

### Lightman's Currency Version

2.1.1.2

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

You don`t get coins whe kiling mobs single-player and on servers

### To Reproduce

1.Enter in game
2.Spawn a mod
3.nothing drops besides mod drops

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrency/files/11534616/latest.log)

**Comment by Lightman314** [comment]
Please provide a copy of the following:
The servers copy of the `lightmanscurrency-common.toml` config file. (located within the servers `config` folder.

**Comment by Denis0819** [comment]
#Common configuration settings
[common]
	#Level of debug messages to be shown in the logs.
	#0-All debug messages. 1-Warnings/Errors only. 2-Errors only. 3-No debug messages.
	#Note: All debug messages will still be sent debug.log regardless of settings.
	#Range: 0 ~ 3
	debugLevel = 0

	#Crafting Settings.
	[common.crafting]
		#Whether Network Traders can be crafted.
		#Disabling will not remove any existing Network Traders from the world, nor prevent their use.
		#Disabling does NOT disable the recipes of Network Upgrades or the Trading Terminals.
		#/reload required for changes to take effect.
		allowNetworkTraderCrafting = true
		#Whether Trader Interface blocks can be crafted.
		#Disabling will not remove any existing Trader Interfaces from the world, nor prevent their use.
		#/reload required for changes to take effect.
		allowTraderInterfaceCrafting = true
		#Whether Auction Stand blocks can be crafted.
		#Disabling will not remove any existing Auction Stands from the world, nor prevent their use.
		#/reload required for changes to take effect.
		allowAuctionStandCrafting = true

	#Villager Related Settings.
	#Note: Any changes to villagers requires a full reboot to be applied due to how Minecraft/Forge registers trades.
	[common.villagers]
		#Whether the wandering trader will have additional trades that allow you to buy misc items with money.
		addCustomWanderingTrades = true
		#Whether the banker villager profession will have any registered trades. The banker sells Lightman's Currency items for coins.
		addBanker = true
		#Whether the cashier villager profession will have any registered trades.. The cashier sells an amalgamation of vanilla traders products for coins.
		addCashier = true

		#Settings Related to other Villagers
		[common.villagers.other_traders]
			#Whether vanilla villagers should have the Emeralds from their trades replaced with coins.
			changeVanillaTrades = true
			#Whether villagers added by other mods should have the Emeralds from their trades replaced with coins.
			changeModdedTrades = false
			#Whether the wandering trader should have the emeralds from their trades replaced with the default trader coin.
			changeWanderingTrades = false
			#The default coin to replace a traders emeralds with.
			defaultTraderCoin = "lightmanscurrency:coin_emerald"
			#List of trader coin overrides.
			#Each entry must be formatted as follows: "mod:some_trader_type-lightmanscurrency:some_coin"
			#Every trader not on this list will use the default trader coin defined above.
			traderOverrides = ["minecraft:butcher-lightmanscurrency:coin_iron", "minecraft:cartographer-lightmanscurrency:coin_iron", "minecraft:farmer-lightmanscurrency:coin_iron", "minecraft:fisherman-lightmanscurrency:coin_iron", "minecraft:fletcher-lightmanscurrency:coin_copper", "minecraft:leatherworker-lightmanscurrency:coin_iron", "minecraft:mason-lightmanscurrency:coin_iron", "minecraft:shepherd-lightmanscurrency:coin_iron"]

	#Loot item customization. Accepts item ids (i.e. lightmanscurrency:coin_copper).
	#Input 'minecraft:air' to not spawn loot of that tier (so that you can use higher-tier spawn rates without the presence of lower-tier loot).
	[common.loot_customization]
		#T1 loot item. Used for T1-T6 entity & chest loot drops.
		lootItemT1 = "lightmanscurrency:coin_copper"
		#T2 loot item. Used for T2-T6 entity & chest loot drops.
		lootItemT2 = "lightmanscurrency:coin_iron"
		#T3 loot item. Used for T3-T6 entity & chest loot drops.
		lootItemT3 = "lightmanscurrency:coin_gold"
		#T4 loot item. Used for T4-T6 entity & chest loot drops.
		lootItemT4 = "lightmanscurrency:coin_emerald"
		#T5 loot item. Used for T5-T6 entity & chest loot drops.
		lootItemT5 = "lightmanscurrency:coin_diamond"
		#T6 loot item. Used for T6 entity & chest loot drops.
		lootItemT6 = "lightmanscurrency:coin_netherite"

	#Entity loot settings. Accepts entity ids (i.e. minecraft:zombie)
	[common.entity_loot]
		#Whether coins can be dropped by entities. Does not effect chest loot generation.
		enableEntityDrops = true
		#Whether coins can be dropped by entities that were spawned by the vanilla spawner.
		enableSpawnerEntityDrops = false
		#Whether modded machines that emulate player behaviour can trigger coin drops from entities.
		#Set to false to help prevent coin farming.
		allowFakePlayerTrigger = true
		#Entities that will occasionally drop T1 loot.
		entityListT1 = []
		#Entities that will occasionally drop T1 -> T2 loot.
		entityListT2 = []
		#Entities that will occasionally drop T1 -> T3 loot.
		entityListT3 = []
		#Entities that will occasionally drop T1 -> T4 loot.
		entityListT4 = []
		#Entities that will occasionally drop T1 -> T5 loot.
		entityListT5 = []
		#Entities that will occasionally drop T1 -> T6 loot.
		entityListT6 = []
		#Entities that will drop a large amount of T1 loot.
		bossEntityListT1 = []
		#Entities that will drop a large amount of T1 -> T2 loot.
		bossEntityListT2 = []
		#Entities that will drop a large amount of T1 -> T3 loot.
		bossEntityListT3 = []
		#Entities that will drop a large amount of T1 -> T4 loot.
		bossEntityListT4 = []
		#Entities that will drop a large amount of T1 -> T5 loot.
		bossEntityListT5 = []
		#Entities that will drop a large amount of T1 -> T6 loot.
		bossEntityListT6 = []

	#Chest loot settings.
	[common.chest_loot]
		#Whether coins can spawn in chests Does not effect entity loot drops.
		enableChestLoot = true
		#Chests that will occasionally spawn T1 loot.
		chestListT1 = []
		#Chests that will occasionally spawn T1 -> T2 loot.
		chestListT2 = []
		#Chests that will occasionally spawn T1 -> T3 loot.
		chestListT3 = []
		#Chests that will occasionally spawn T1 -> T4 loot.
		chestListT4 = []
		#Chests that will occasionally spawn T1 -> T5 loot.
		chestListT5 = []
		#Chests that will occasionally spawn T1 -> T6 loot.
		chestListT6 = []

**Comment by Denis0819** [comment]
[lightmanscurrency-common.txt](https://github.com/Lightman314/LightmansCurrency/files/11534732/lightmanscurrency-common.txt)
I changed it to text bc you can`t send .toml files on github

**Comment by Lightman314** [comment]
`
entityListT1 = []
entityListT2 = []
entityListT3 = []
entityListT4 = []
etc...`

No entities are configured to drop coins, and thus no mobs will drop them.
Did you edit this at some point, or is my mod not generating the default entries properly?

**Comment by Denis0819** [comment]
I never edited it

**Comment by Denis0819** [comment]
Should i just add every entity by hand?

**Comment by Lightman314** [comment]
> Should i just add every entity by hand?

You can do that if you need to, but for now here's a properly generated "default config" that you can use if you want.

[lightmanscurrency-common.toml.txt](https://github.com/Lightman314/LightmansCurrency/files/11539196/lightmanscurrency-common.toml.txt)

**Comment by Lightman314** [comment]
I know you already closed this, but this has now been officially fixed in v2.1.1.4 (v2.1.1.0d for any 1.19.3 players).
