### ISSUE TITLE
Creative Stores

### ISSUE THREAD

**Issue by Chassx2** [Lightman314/LightmansCurrency#129]
I currently run a public general store and having to keep it stock in creative is a pain. Would there be a feature to toggle as 'Creative' for Ops?

**Comment by Lightman314** [comment]
The feature you are asking for has existed for years...

Please read the FAQ (can be found [here](https://github.com/Lightman314/LightmansCurrency/wiki/Frequently-Asked-Questions#how-do-i-make-a-trader-with-infinite-stock)) and wiki to make sure that the feature you're requesting doesn't already exist before posting a feature request.
