### ISSUE TITLE
How to forcibly access a user's bank account.

### ISSUE THREAD

**Issue by WhiteNoise1010** [Lightman314/LightmansCurrency#135]
Is there a way to force money out of a particular player's bank account?

I am currently writing a custom economic system using kubeJS.
However, I don't know how to access the player's bankbook through commands or events.
For example, you cannot forcefully take money from the player when you want to collect taxes, take fines, or pay money when interacting with a particular machine.

I can give money to the player using the /lcadmin giveMoneyToBankAccounts command, but I don't know how to take it.

**Comment by Lightman314** [comment]
1- Please do not use the Feature Request/Issue Report feature to ask questions. You can either ask on the discord, on in the curseforge comment section.
2- Also, please check the wiki for the [answer to your question](https://github.com/Lightman314/LightmansCurrency/wiki/Bank-Accounts-&-ATM#account-admin-selection) before asking regardless, cause I can promise you the [answer is there](https://github.com/Lightman314/LightmansCurrency/wiki/Bank-Accounts-&-ATM#account-admin-selection)!
