### ISSUE TITLE
BUG: Infinite loop with Multi-Blocks

### ISSUE THREAD

**Issue by jehkael** [Lightman314/LightmansCurrency#140]
### Minecraft Version

1.19.2

### Forge Version

net.minecraftforge:43.2.8

### Lightman's Currency Version

2.1.0.0d

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

infinite loop error occur and server stops (it also occurs in 2.1.0.0f)
[crash-2023-08-13_13.14.20-server.txt](https://github.com/Lightman314/LightmansCurrency/files/12328820/crash-2023-08-13_13.14.20-server.txt)

### To Reproduce

log in and await a while then the crash occurs

### Screenshots/Logs/Crash Reports

[crash-2023-08-13_13.14.20-server.txt](https://github.com/Lightman314/LightmansCurrency/files/12328819/crash-2023-08-13_13.14.20-server.txt)

**Comment by jehkael** [comment]
this crush happens through 2.1.0.0a to f

**Comment by Lightman314** [comment]
Should be fixed in 1.16.5-2.1.0.0h and 1.19.2-2.1.0.0g.

Will be fixed in the 2.1.2.3 update for 1.18.2/1.19.4/1.20.1.

**Comment by Lightman314** [comment]
Fixed in v2.1.2.3
