### ISSUE TITLE
BUG: Setting Price In Vending Machine Results In Crash

### ISSUE THREAD

**Issue by VillagerWerman** [Lightman314/LightmansCurrency#141]
### Minecraft Version

1.20.1

### Forge Version

47.1.0

### Lightman's Currency Version

lightmanscurrency-1.20.1-2.1.2.2c.jar

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

When trying to set the price for a vending machine games crashes

### To Reproduce

1. Place vending machine.
2. Access GUI.
3. Click on "Set Price" for one of the vending machine slots.

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrency/files/12343865/latest.log)
[crash-2023-08-15_13.43.29-client.txt](https://github.com/Lightman314/LightmansCurrency/files/12343867/crash-2023-08-15_13.43.29-client.txt)

**Comment by Lightman314** [comment]
Duly noted. Will be fixed in the next update.

**Comment by Lightman314** [comment]
Fixed in v2.1.2.3
