### ISSUE TITLE
Feature Request: Villager/Wandering Trader interaction

### ISSUE THREAD

**Issue by KatoNamus** [Lightman314/LightmansCurrency#142]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to check the price a villager/wandering trader is asking, close the GUI, open wallet, remove the coins I need, find the villager/trader again and then trade again. And then some times you can't trade because the wallet converted my coins to (e.g.) 1d 0e 0i 0c and the villager/trader's item costs x emerald coins.

**Describe the solution you'd like**
When clicking on a villager/trader's offered ware, auto-populate the coin value from my wallet. And if I don't have the exact change for the trade, down-convert my current coins in order to make the trade. E.g. if I have 1d 1e 1i 1c but I want to purchase a 2e item, convert my 1d to emerald coins so I can make the purchase. All without having to close the trading GUI and manually getting the coins from my wallet

**Describe alternatives you've considered**
Install [Numismatic Overhaul: Reforged](https://www.curseforge.com/minecraft/mc-mods/numismatic-overhaul-reforged) which does this but the rest of its features suck when compared to LC

**Additional context**
This is obviously mostly concerned with SSP but I believe it applies to SMP too.

**Comment by Lightman314** [comment]
To be honest, the main reason I didn't bother doing this was because I didn't think it was possible. That said, if NOR has done it, then it must be possible in some form. I'll see if I can implement this in some form in the next update.

**Comment by KatoNamus** [comment]
Thank you very much 😁
