### ISSUE TITLE
Feature Request: Banker NPC / Villager Job

### ISSUE THREAD

**Issue by jasons49** [Lightman314/LightmansCurrency#143]
I just wanted to say I've banged my head on the wall for how many times I've messed up where this request belongs I'm very sorry for the headache my stupidity has caused.

**Is your feature request related to a problem? Please describe.**
My server's theme is Medieval to Rennaissance and we love this mod except for the modern items, now we've removed the recipes for most of those items so they can't be crafted, but the ATM ans Mint IS also too modern.

**Describe the solution you'd like**
What would be awesome that could be a good alternative for those non-modern server's is a
- Banker NPC
- Or a Villager profession called Banker (their job allows you to access your bank account when you interact with them) 
- allowing for something like a grand exchange or Bank (without being modern)
For the Mint item an alternative would be
-Add Banker npc 
- Or villager profession called a minter, 
- or add minting as an ability that the Banker NPC or Villager profession can do when you give them metal ingots vs putting them in your bank account.

**Describe alternatives you've considered**
I've considered other mods but lightman's is the best of the currency mods that don't add modern currency or anything game breaking. I'd also considered old timey looking items to be alternatives to the modern mint and ATM but I don't know what they would be other than what I've suggested.

**Additional context**
Mods that add more villager jobs are "More villger professions", "More villagers".

**Comment by Lightman314** [comment]
Unfortunately my mod already adds a banker villager, so it'd be extremely confusing to add another.
Also, adding a banker NPC of any variety would be extremely inconvenient as the ATM's features are something that should be easily accessible to anyone (as it is in its current state, as the ATM can be crafted with fairly common resources), and unless the NPC was somehow craftable, it's not a realistic solution to the problem.

As far as I can see, the easiest and best solution would simply be to make a resource pack that changes the models/textures of the ATM, Coin Mint, etc to be more "lore friendly".

**Comment by Lightman314** [comment]
As much as I understand your concerns with theming, this issue seems like it can easily be solved with a proper resource pack that remodels and/or re-textures the ATM and other problematic blocks that don't fit the theme with their default textures (or for the vending machines, simply using CraftTweaker to disable their recipes and hiding them from JEI, etc.)
