### ISSUE TITLE
BUG: wallet deleting coins when closed

### ISSUE THREAD

**Issue by Gunz-18** [Lightman314/LightmansCurrency#145]
### Minecraft Version

1.18.2

### Forge Version

40.2.0 

### Lightman's Currency Version

2.1.2.3

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

when putting money in any of the wallets and then closing them and opening them they delete all the money

### To Reproduce

open wallet
put money inside
close wallet
open wallet -money gone

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrency/files/12618804/latest.log)

**Comment by Lightman314** [comment]
Issue confirmed. Fortunately it only appears to only happen to the 1.18 version.
Either way, I'll try to get a fix for this out by tonight.

**Comment by Lightman314** [comment]
Fixed in LC 1.18.2-2.1.2.3a
