### ISSUE TITLE
Root advancement isn't granted by default

### ISSUE THREAD

**Issue by vizthex123** [Lightman314/LightmansCurrency#147]
### Minecraft Version

1.18.2

### Forge Version

40.2.10

### Lightman's Currency Version

2.2.1.3a

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

The root advancement for the tree isn't granted by default, even though other mods (and Minecraft itself) grant them by default in order to make the tree visible.

### To Reproduce

1) Install the mod
2) Make a new world
3) Open the advancement menu
4) See that the Minecraft ones are there by default but Lightman's Currency isn't

### Screenshots/Logs/Crash Reports

![image](https://github.com/Lightman314/LightmansCurrency/assets/31721920/08ae7d44-7d1b-43f2-80fa-c21075004d34)
![image](https://github.com/Lightman314/LightmansCurrency/assets/31721920/aa3443e4-4231-4fd5-bca2-4364657ad061)

**Comment by Lightman314** [comment]
Root advancement will now be obtained using the same criteria as My First Penny advancement in v2.1.2.4 and newer.

**Comment by vizthex123** [comment]
> Root advancement will now be obtained using the same criteria as My First Penny advancement in v2.1.2.4 and newer.
> 
> During testing I also discovered that the My First Penny advancement was using an out-of-date coin tag, and thus could not be earned properly.

Yeah, I noticed that in my world too. Would be great to have it fixed. I'd also say to remove one and make the remaining one the root. No need to have 2 advancements for the same thing, right?

Was about to post that the Minecraft one is granted by having a crafting table in your inventory, but doesn't print in chat (which is something most roots use do as far as i can tell).
![image](https://github.com/Lightman314/LightmansCurrency/assets/31721920/6ff8a4bd-4d53-43ca-98fa-3bea5236f9a4)

**Comment by vizthex123** [comment]
logged in (in my 1.19.2 pack) and got "my first penny!" but the root is still not granted.

![image](https://github.com/Lightman314/LightmansCurrency/assets/31721920/f619c133-8fbb-458c-964a-066722f69d1c)

**Comment by Lightman314** [comment]
That's because this is only fixed in the latest 1.20.1 release...

**Comment by vizthex123** [comment]
> That's because this is only fixed in the latest 1.20.1 release, hence why the ticket is still open...

ah, didn't realize that. Haven't made a 1.20 pack yet.

**Comment by Lightman314** [comment]
2.1.2.4 has been ported to 1.18.2, and thus this issue has been resolved!

**Comment by vizthex123** [comment]
awesome, thanks.
