### ISSUE TITLE
BUG: Crash when equipping wallet

### ISSUE THREAD

**Issue by emanuele246gi** [Lightman314/LightmansCurrency#148]
### Minecraft Version

1.18.2

### Forge Version

40.2.10

### Lightman's Currency Version

2.1.2.3a

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

You will see them in the crash report

### Describe the bug

The game crashed when I equipped the wallet, I don't know if the fact that it contained money affected it or not.

### To Reproduce

Equip the wallet in the LC's slot

### Screenshots/Logs/Crash Reports

https://pastebin.com/EJkyge05

**Comment by Lightman314** [comment]
Fixed in v2.1.2.4, but this fix has not yet been ported to 1.18.

**Comment by Lightman314** [comment]
2.1.2.4 is now ported to 1.18.2, and thus this issue has been resolved.
