### ISSUE TITLE
BUG: Move coins into wallet stopped working

### ISSUE THREAD

**Issue by RaidenKoizuma** [Lightman314/LightmansCurrency#152]
### Minecraft Version

1.20.1

### Forge Version

Forge 47.2.4

### Lightman's Currency Version

2.1.2.4b

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

Clicking the button to move coins from container to wallet does nothing when clicked. It's worth mentioning it worked in a previous version of the mod (2.1.2.4a I believe)

### To Reproduce

1. Place coins in an oak chest.
2. Equip wallet (tried copper and gold)
3. Click button and see it does nothing
4. 

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrency/files/13387406/latest.log)

**Comment by Lightman314** [comment]
This is a known issue, and will be fixed in the next update. Thanks for reporting nonetheless :)

**Comment by Lightman314** [comment]
Fixed for 1.20.1 in v2.2.0.0
Will post a mini update for 1.18.2/1.19.2 to fix this for them as well before I work on giving them the new changes.

**Comment by Lightman314** [comment]
Fixed for 1.18.2 & 1.19.2 in v2.1.2.5.
