### ISSUE TITLE
BUG: Crash on saving Persistent Traders

### ISSUE THREAD

**Issue by RaidenKoizuma** [Lightman314/LightmansCurrency#153]
### Minecraft Version

1.20.1

### Forge Version

Forge 47.2.4

### Lightman's Currency Version

2.1.2.4b

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

Tried to save persistent trader with 6 trades in it which has previously worked in last version w/ "M&S Stones" and "server2" as name and id respectively. Seems to happen randomly.

### To Reproduce

1. Setup a trader with 6 trades of modded items.
2. Attempt to save it w/ "M&S Stones" and "server2" as name and id respectively.
3. Crash.

### Screenshots/Logs/Crash Reports

![image](https://github.com/Lightman314/LightmansCurrency/assets/80659327/01f4703b-8885-4745-aa34-70c40464c880)

[crash-2023-11-17_00.29.32-client.txt](https://github.com/Lightman314/LightmansCurrency/files/13387692/crash-2023-11-17_00.29.32-client.txt)

**Comment by Lightman314** [comment]
Should be fixed in v2.2.0.0
Will post a mini-update to fix this for 1.18.2/1.19.2 before updating them to 2.2.0.0

**Comment by Lightman314** [comment]
Fixed for 1.18.2 & 1.19.2 on v2.1.2.5.
