### ISSUE TITLE
Feature Request: {Integration with OPAC to purchase claimblocks}

### ISSUE THREAD

**Issue by BakedSam** [Lightman314/LightmansCurrency#155]
**I'd like for players to be able to buy additional claimblocks through [Open Parties & Claims](https://modrinth.com/mod/open-parties-and-claims)**  

There's currently no way to increase a players claimblocks that I'm aware of without adding a bonusChunkClaims number, but that would require me to use /functions and weird hacks to purchase them with LC. 

Having a way somehow to allow players to buy additional claimblocks from the server for a configurable amount of LC would be awesome

**Comment by Lightman314** [comment]
As much as I'd like to add this compatibility, they don't have a built in method of adding bonus claims/forceloads via a command like FTB Chunks does, nor do they have any form of MaxClaimProvider API like Cadmus does.

Without anything along those lines I cannot implement any method of purchasing additional claims or forceloads without a ridiculous amount of work on my part that just isn't worth it unfortunately.

**Comment by mikes4b22** [comment]
Would it be possible to implement this feature with FTB chunks and ranks then? I've been looking for a clean implementation for this sort of functionality.
