### ISSUE TITLE
BUG: Crash when editing vending blocks / NoSuchMethodError: [...]api.traders.menu.storage.ITraderStorageMenu.m_142621_()

### ISSUE THREAD

**Issue by Yldales** [Lightman314/LightmansCurrency#157]
### Minecraft Version

1.20.1

### Forge Version

47.2.17

### Lightman's Currency Version

1.20.1-2.2.0.0 

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

Editing entries of vending blocks (exemple: Slot Machine) cause the game to crash.

### To Reproduce

1. Place a Slot Machine.
2. Interact with the Slot Machine.
3. Click on the _Open Trader Storage_.
4. Drag'n'drop an item from the player's inventory to one of the entries.
![image](https://github.com/Lightman314/LightmansCurrency/assets/50544935/356807c8-58cd-4bf5-b3c9-22adce570ac6)
5. The game should crash.

### Screenshots/Logs/Crash Reports

- [crash-2023-12-18_23.32.08-client.txt](https://pastebin.com/raw/RkQxqPdJ)

**Comment by Lightman314** [comment]
Fixed in v2.2.0.0a. Thank you for reporting!
