### ISSUE TITLE
BUG: Players able to withdraw more coin then in bankaccount

### ISSUE THREAD

**Issue by LuzioSH** [Lightman314/LightmansCurrency#161]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Lightman's Currency Version

1-2.20.0b

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

player was able to withdraw a full netherite coin when only having a diamond coin in the banl

### To Reproduce

go to the ATM withdraw any coin over current bankaccount limit and receive the coin over limit in inventory

### Screenshots/Logs/Crash Reports

![2023-12-25_22 02 30](https://github.com/Lightman314/LightmansCurrency/assets/154839542/ee12965c-d449-4bd7-a759-668fc2a4a5dc)
![2023-12-25_22 02 35](https://github.com/Lightman314/LightmansCurrency/assets/154839542/bc8247d8-6ad0-4a93-b84c-5faa5e44bf60)
![2023-12-25_22 02 40](https://github.com/Lightman314/LightmansCurrency/assets/154839542/57192da5-77cc-458c-82d8-74066fe7e247)
![2023-12-25_22 02 45](https://github.com/Lightman314/LightmansCurrency/assets/154839542/9d4e4c43-7a5e-4205-94cb-d04425d7c1e6)

**Comment by Lightman314** [comment]
Fixed in v2.2.0.0e. Thank you for reporting!
