### ISSUE TITLE
BUG: Wallet cleared after upgrade 

### ISSUE THREAD

**Issue by LuzioSH** [Lightman314/LightmansCurrency#163]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Lightman's Currency Version

1-2.2.0.0e

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

Had some coins in a wallet when upgrading this wallet with coin in it deleted all coin from wallet

### To Reproduce

go to your wallet, insert x amount of coin, upgrade said wallet to x stage, Empty wallet.

### Screenshots/Logs/Crash Reports

![2023-12-28_21 46 32](https://github.com/Lightman314/LightmansCurrency/assets/154839542/1fe43e2e-53a6-4cb0-87d6-c10244412346)
![2023-12-28_21 47 03](https://github.com/Lightman314/LightmansCurrency/assets/154839542/bfe8bfaa-68e4-4560-8e49-9567aa61c452)
![2023-12-28_21 48 26](https://github.com/Lightman314/LightmansCurrency/assets/154839542/4e20036a-6304-46e0-adca-9241075fce0d)
![2023-12-28_21 48 34](https://github.com/Lightman314/LightmansCurrency/assets/154839542/a74d80d1-ef26-4f0f-bfd9-c7e999e87ad2)

**Comment by Lightman314** [comment]
Don't know why this randomly broke, cause I haven't touched the code for this recipe in ages, but it was happening, so I've simplified the code for these recipes and that seems to have fixed the issue.
Fixed in v2.2.0.0f. Thank you for reporting!
