### ISSUE TITLE
BUG: Duping Glitch (MAJOR)

### ISSUE THREAD

**Issue by CorranEveryone** [Lightman314/LightmansCurrency#164]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Lightman's Currency Version

1.20.1-2.2.0.0e

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

It allows for infinite coins

### To Reproduce

1. Make a Coinpile
2. Put it in your wallet
3. Go into the bank menu
4. Put in 9 coins of the type you have
5. Press deposit
6. Done! (Notice you have put the coins in the bank account but it is also still in your wallet)

### Screenshots/Logs/Crash Reports

All I will tell you is that my friend had 1006n.

**Comment by Lightman314** [comment]
Fixed in v2.2.0.0f. Thank you for reporting!

**Comment by CorranEveryone** [comment]
Thanks! My friend was going to remove this mod but i stopped him saying that i can ask him to get it fixed by letting you know about it! Thanks for being quick about it too!
