### ISSUE TITLE
 Customize the casting formula for "Coin Mining Machine"

### ISSUE THREAD

**Issue by QianMuu** [Lightman314/LightmansCurrency#165]
I want to customize the recipe for Coin Mining Machine.

Just like, a copper mine is minted into 32 copper coins.

I will use Craftweaver to customize the recipe,

But I don't know what its code looks like.

**Comment by Lightman314** [comment]
Please fill out the entire Feature Request form, don't just delete the questions/template and write your own thing, as what you've given doesn't in any way tell me what you are requesting...
