### ISSUE TITLE
BUG: Creative Search Menu Does Not Work

### ISSUE THREAD

**Issue by zontreck** [Lightman314/LightmansCurrency#167]
### Minecraft Version

1.20.1

### Forge Version

47.2.18

### Lightman's Currency Version

2.2.0.0g

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

while using the mod, the creative search tab is non-functional and appears empty.

### To Reproduce

Use this mod, try to use creative search

### Screenshots/Logs/Crash Reports

No crash log

**Comment by Lightman314** [comment]
![image](https://github.com/Lightman314/LightmansCurrency/assets/4554273/b4a0195d-f3c4-4409-b71a-402d9a9630f3)
Unable to replicate in my dev environment. Please attach a copy of your clients latest.log so that I can inspect it for errors.

**Comment by zontreck** [comment]
Upon further testing this happens with a mod (and its dependencies), Botania. The bug goes away when either botania or lightman's currency are removed. Here is both the server and client log. If it is not a bug with lightman's i'll file this with botania.
[client.log](https://github.com/Lightman314/LightmansCurrency/files/13867020/client.log)
[server.log](https://github.com/Lightman314/LightmansCurrency/files/13867023/server.log)

**Comment by Lightman314** [comment]
I figured out the issue I believe, and I'm actually amazed that this isn't an issue that occurs regardless of botania's presence.

Either way, I'll make sure to fix this in the next build, as v2.2.0.1 will finish stabilizing the changes I made in v2.2 (as v2.2.0.0 was slightly rushed since I wanted to get it out before Christmas so I could add the Christmas event).

**Comment by Lightman314** [comment]
Also, as an FYI, if you'd still like to be able to play in the meantime, downgrading LC to v2.1.2.5 should fix the crash, although it will cause problems if the world was actually loaded and has data saved by LC 2.2.0.0 as that version has a lot of changes in how data is saved that v2.1.2.5 won't know about.

**Comment by Lightman314** [comment]
Fixed in v2.2.0.1
