### ISSUE TITLE
BUG: coinDropPercentage gamerule not working

### ISSUE THREAD

**Issue by AnyankaT** [Lightman314/LightmansCurrency#168]
### Minecraft Version

1.20.1

### Forge Version

47.1.3

### Lightman's Currency Version

1.20.1-2.1.2.4b

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

Corail Tombstone 8.5.6-1.20.1

### Describe the bug

On our dedicated server, we have set the gamerule coinDropPercent to 50 to encourage bank accounts. However, the wallets do not drop any coin on death. 

I believe this is a conflict with tombstone, which has a setting for chance of item loss on death (currently set to 0). Is there any way to work with the folks at Corail Tombstone so that that setting ignores the wallet, or whatever, to have coins drop on death?

### To Reproduce

1. have a wallet with coins.
2. die.
3. wallet is kept in curios slot, but no coins are gone.

### Screenshots/Logs/Crash Reports

[debug-1.log.gz](https://github.com/Lightman314/LightmansCurrency/files/13903020/debug-1.log.gz)

**Comment by Lightman314** [comment]
This is an issue that was fixed for 1.20.1 in v2.2.0.0c. Please update to the latest version of the mod to receive this fix.
