### ISSUE TITLE
[Feature Request] Trading Machines auto-refill

### ISSUE THREAD

**Issue by HonzaVinCZ** [Lightman314/LightmansCurrency#17]
One more thing I found missing to me is automatically refilled traders. I couldn't find a way how to fill my stock by hoppers or Applied Energetics so I think they can't be automatically refilled at all. 
It would be another cool feature but I understand that it couldn't work with your security system that allows only owner or allowed players to open the storage.

**Comment by Lightman314** [comment]
I've already implemented something similar on LCTech with the ability to pump in/out fluids, so I could probably add the ability enable item interactions with the traders. It may require any existing multi-block traders to be torn down and re-built for the new feature to work, as I'll need to put interfacing block entities on the additional blocks that don't actually have the traders data, but it should be possible.

It may take a while though, as I'm probably going to take this opportunity to give the traders full on security settings (currently only on an owner, ally, none basis) a major overhaul, allowing allies to have defined permissions (ability to collect money, clear the shops logger, add/remove allies, edit trade rules, etc.), perhaps even allowing the transfer of ownership to another player. And in this new Trader Settings Menu, will also be some additional settings along the lines of allowing external item placement, and allowing external item draining which will basically be how this will be implemented.

**Comment by HonzaVinCZ** [comment]
Wow, that are some big plans! Definitely I'm looking forward to see these features in your mod because I already like it a lot. I was looking for some chestshop alternative and this mod is just all in one. Economy, shops, remote shops and even fluid shops. 

Just an idea I got was you might get some inspiration of Thermal Expansion machines where owner could set import/export for each side and set the machine private or public.

![tab-configuration](https://user-images.githubusercontent.com/29098779/147886905-bd1742ed-981f-4669-90e7-b53d4e8adb45.png)
_Blue: Import
Orange: Export_

If you left your traders as they are, that way it could work on the back side where pipes/hoppers could be connected and hidden in wall.

**Comment by Lightman314** [comment]
Just a quick update, I've got it working on the normal traders as intended on 1.16, but there's still a few things to do before the 1.16 version is ready. Then I'll need to also port the changes over to 1.18 and do some testing there, so it will probably be a few more days. That said, I've gotten most of the road blocks out of the way so it should be smooth sailing from here on out.

Also, here's what the new Import/Export settings tab looks like if you're interested:
![image](https://user-images.githubusercontent.com/4554273/148271178-6d1f647e-2006-4023-a25e-4edc9b68c7db.png)

**Comment by HonzaVinCZ** [comment]
I personally think that is perfect. I'd never think the GUI could look that familiar to me already. Well done and thank you. Can't wait to test it myself!

**Comment by Lightman314** [comment]
Implemented in v1.0.2.0.
