### ISSUE TITLE
Feature Request: Better intergration with FTB Chunks

### ISSUE THREAD

**Issue by kiritodragneel** [Lightman314/LightmansCurrency#171]
FTB Chunks is a great protection plugin but lacks some rental features that let people build homes/cities and rent them to players. 
It would be GREAT if LMC could allow players to rent their FTB Chunk claims to other players for set periods of times.

**Comment by Lightman314** [comment]
While I like this idea, I don't really have the desire or skills required to change core FTB Chunks functionality that would be required to make this happen. That said, in the future I would love to be able to make an LC expansion mod that does just this, but it's unlikely for that to happen any time soon.
