### ISSUE TITLE
Feature Request: Sales Logger, Better notifications, etc.

### ISSUE THREAD

**Issue by AylanJ123** [Lightman314/LightmansCurrency#172]
**Is your feature request related to a problem? Please describe.**
I feel overwhelmed when trying to see what has been sold and what needs to be restocked. Depending on the size of the shop, something can go out of stock for days until you notice (If no one directly tells you). Specially if the server is heavily active, all sort of notifications get buried in the chat.

**Describe the solution you'd like**
A sales logger, a mailbox or an accounting desk. Something that might keep the theme of machines and accounting. Some sort of UI or block that you can access to in order to know what has been sold, when, by who and for how much.

**Describe alternatives you've considered**
At the very least, a filter for sales notifications can be added to the current logs of each stand. Also, it can have a colorful border or colorful characters to make it stand out of normal changes, restock and renaming. Also, the cash register could have a global log of all stands.

**Comment by Lightman314** [comment]
Have you tried enabling notifications in your traders [Notification Settings](https://github.com/Lightman314/LightmansCurrency/wiki/Trading-Machines#notifications-tab)?

With trader notifications enabled, you'll receive each sale & out of stock notification in your personal notification screen (accessible via the `!!!` button in the top-right of your inventory menu. *wiki page still pending*). Notifications viewed there will also have a yellow frame if not yet flagged as read, and can be filtered by notification source (trader, auction house, bank account, etc.) allowing you to look at a specific traders notifications and look at its highlighted notifications for any "Out of Stock" warnings from anywhere in the world (including wherever the actual items you need to restock can be collected from).

**Comment by AylanJ123** [comment]
> Have you tried enabling notifications in your traders [Notification Settings](https://github.com/Lightman314/LightmansCurrency/wiki/Trading-Machines#notifications-tab)?
> 
> With trader notifications enabled, you'll receive each sale & out of stock notification in your personal notification screen (accessible via the `!!!` button in the top-right of your inventory menu. _wiki page still pending_). Notifications viewed there will also have a yellow frame if not yet flagged as read, and can be filtered by notification source (trader, auction house, bank account, etc.) allowing you to look at a specific traders notifications and look at its highlighted notifications for any "Out of Stock" warnings from anywhere in the world (including wherever the actual items you need to restock can be collected from).

Well, that's the exact solution I needed for all my problems. Then maybe just tell about this button somewhere in a manual or the wiki, somewhere more visible.

It went completely over my sight. Thanks a lot!!!
