### ISSUE TITLE
BUG: Upon clicking any block, I get "The game crashed whilst unexpected error Error: java.util.NoSuchElementException: null" 1.20.2

### ISSUE THREAD

**Issue by Lovingtaken3** [Lightman314/LightmansCurrency#174]
### Minecraft Version

1.20.2

### Forge Version

48.1.0

### Lightman's Currency Version

2.1.2.4a

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

Upon clicking on any block, The game crashed whilst unexpected error
Error: java.util.NoSuchElementException: null

### To Reproduce

Download MCrashCraft Modpack, enter singleplayer or an MCrashCraft modpack server, click on any of Lightman's Currency mod blocks. Game crashes.

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrency/files/13999493/latest.log)
![image](https://github.com/Lightman314/LightmansCurrency/assets/17980552/cb3b1d48-b0fc-479f-8af7-3673ceaccd4d)
[crash-2024-01-20_18.25.34-client.txt](https://github.com/Lightman314/LightmansCurrency/files/13999497/crash-2024-01-20_18.25.34-client.txt)

**Comment by Lovingtaken3** [comment]
Version meant to say 2.1.2.4a

**Comment by Lightman314** [comment]
Tested in dev with this exact forge version (just in case it changed anything) and was unable to replicate this issue.

In addition to that, the crash mentioned in the crash report has to do with the toast rendering system (the things that appear in the corners when you unlock recipes or get an advancement), and has nothing to do with my mod. Why it's only encountering an error when one of my blocks is interacted with is beyond me, but I never touch the toast code in any way, shape, and/or form and my mods code/classes aren't mentioned in the crash report, nor is any unexpected behavior seen in the latest.log provided.

If it'd help you in your search for answers though, `nochatreports` has a mixin modifying the Toast class that is mentioned several times within the crash report. For more info see the end of the stacktrace at lines 11 & 14:
`{re:classloading,pl:mixin:APP:mixins/common/nochatreports.mixins.json:client.MixinToastComponent,pl:mixin:A,pl:runtimedistcleaner:A}`

**Comment by Lovingtaken3** [comment]
I found a fix, I ran /advancement grant @a everything, and waited for all of the advancements to get finish/ for the toast notification to get cleared, it now works perfect.
