### ISSUE TITLE
Crash on startup Memory leak potential

### ISSUE THREAD

**Issue by Cha3son** [Lightman314/LightmansCurrency#175]
### Minecraft Version

1.20.1

### Forge Version

47.2.17

### Lightman's Currency Version

v2.2.0.1

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

Startup server and when it loads to lightmanscurrency. It will crash and shutdown. Crash log shows that it runs out of memory when loading lightmanscurrency. Reverting Back to previous version seems to be ok.
[crash-2024-01-22_01.51.49-server.log](https://github.com/Lightman314/LightmansCurrency/files/14004604/crash-2024-01-22_01.51.49-server.log)

### To Reproduce

1. Use Lastest version v2.2.0.1 
2. Launch Server
3. Runs out of memory  when loading lightmanscurrency mod and server crashes 

### Screenshots/Logs/Crash Reports

Startup server and when it loads to lightmanscurrency. It will crash and shutdown. Crash log shows that it runs out of memory when loading lightmanscurrency. Reverting Back to previous version seems to be ok.
[crash-2024-01-22_01.51.49-server.log](https://github.com/Lightman314/LightmansCurrency/files/14004604/crash-2024-01-22_01.51.49-server.log)

**Comment by Lightman314** [comment]
Considering that the crash is happening during the `ServerStartedEvent` I think it's safe to assume that this is not a memory leak, as there would have been no time for any memory to have leaked at this point in the process.

Sadly all I can really say is that whatever server host you are using doesn't have enough memory to run all of the mods that you are attempting to run. I'd suggest increasing the minimum ram argument, cause the crash report also states that it's only using about 3GB of the 10GB available ram?

**Comment by Lightman314** [comment]
Should be fixed in v2.2.0.1a. Thank you for reporting!

*Note*: At the time of closing, Curseforge is having issues with uploading files, so if you need it immediately, you can download it from modrinth [here](https://modrinth.com/mod/lightmans-currency/version/1.20.1-2.2.0.1a)
