### ISSUE TITLE
BUG: Entity loot still dropping coins after turned off

### ISSUE THREAD

**Issue by Sanderk35** [Lightman314/LightmansCurrency#177]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Lightman's Currency Version

2.2.0.1

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

https://www.curseforge.com/minecraft/modpacks/mana-adventures

### Describe the bug

Even when the option is turned off the mobs still drop money

### To Reproduce

1. Turn it off
2. Kill a mob
3. Get money

### Screenshots/Logs/Crash Reports

![Schermafbeelding 2024-01-24 082330](https://github.com/Lightman314/LightmansCurrency/assets/76066612/af2e0ca3-a921-4ae4-91b6-1440201ceec4)

**Comment by Sanderk35** [comment]
Here is another screenshot
![Schermafbeelding 2024-01-24 082556](https://github.com/Lightman314/LightmansCurrency/assets/76066612/28c3827a-256a-4d24-a217-33b04ee01e2e)

**Comment by Lightman314** [comment]
You are editing the wrong config file. As of v2.2.0.1, the `lightmanscurrency-common/client/server.toml` config files are not longer used. Please instead edit the new `lightmanscurrency-common.lcconfig` to configure the mod to your liking.
