### ISSUE TITLE
BUG: Server config not creating

### ISSUE THREAD

**Issue by DuckManO7** [Lightman314/LightmansCurrency#178]
### Minecraft Version

1.19.3

### Forge Version

44.1.23

### Lightman's Currency Version

2.1.1.0d

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

I was playing on a single player world and i wanted to turn on the melt coin, but i descovered that the Server config file is nowhere to be seen, the Server file just doesn't appear.

### To Reproduce

1. Start the game
2. Create a world
3. Check the config folder and notice the server file is the only one missing

### Screenshots/Logs/Crash Reports

![Untitled](https://github.com/Lightman314/LightmansCurrency/assets/157708854/97fb481a-0b6e-4921-9b4a-2846f387728b)
[latest.log](https://github.com/Lightman314/LightmansCurrency/files/14052861/latest.log)

**Comment by Lightman314** [comment]
In pre 2.2.0.1 versions the server cojfig generates within the `world/serverconfig` folder, and on single player worlds this remains true, except it spawns withing the `saves/world_name/serverconfig` folder.

**Comment by DuckManO7** [comment]
> In pre 2.2.0.1 versions the server cojfig generates within the `world/serverconfig` folder, and on single player worlds this remains true, except it spawns withing the `saves/world_name/serverconfig` folder.

Oh, I'm sorry, I didn't know about that.
