### ISSUE TITLE
BUG: "lightmanscurrency-client.lcconfig" does not work correctly on dedicated servers

### ISSUE THREAD

**Issue by DankestO** [Lightman314/LightmansCurrency#179]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Lightman's Currency Version

2.2.0.1b

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

lctech-1.20.1-0.2.1.1

### Describe the bug

It seems that 2.2.0.1 the "lightmanscurrency-client.lcconfig" is not created on the client side when you enter a dedicated server, it is only created when you enter a singleplayer world.

Curiously, to make the client.lcconfig work on the dedicated server you must start a world in singleplayer and then enter the server for the configurations to work.

### To Reproduce

1- Login to a dedicated server (Does not load client.lcconfig configurations)
2- Exit and enter a single player world and re-enter the dedicated server
3- Now client.lcconfig works

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrency/files/14057615/latest.log)

**Comment by Lightman314** [comment]
Now that you mention it, you are correct it would not work correctly (and neither would the client-side common config be created, but that wouldn't have any effect unless you're on a single-player world anyways, but I should at least have it generate it).

I need to make at least one more LC Patch anyways, so I'll make sure this gets fixed then :)

**Comment by Lightman314** [comment]
Should be fixed in v2.2.0.1c. Thank you for reporting!
