### ISSUE TITLE
BUG: I can't connect to the dedicated server

### ISSUE THREAD

**Issue by DankestO** [Lightman314/LightmansCurrency#180]
### Minecraft Version

1.20.1

### Forge Version

47.2.0

### Lightman's Currency Version

2.2.0.1c

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

lctech-1.20.1-0.2.1.1

### Describe the bug

I'm here again, sorry xD
With the latest update, when you enter a dedicated server it does not seem to load at all. I do not understand why.
It loads the terrain, but the text is still there and doesn't let you do anything.

Thank you for your continued hard work on this wonderful mod!

### To Reproduce

1- Enter the dedicated server
2- Wait indefinitely to enter

### Screenshots/Logs/Crash Reports

![Captura de pantalla 2024-01-26 112039](https://github.com/Lightman314/LightmansCurrency/assets/126206944/5ab5d9be-5be0-43e1-8924-6d861245611e)
Server log: [latest.log](https://github.com/Lightman314/LightmansCurrency/files/14063498/latest.log)
Client log: [latest.log](https://github.com/Lightman314/LightmansCurrency/files/14063500/latest.log)

**Comment by Lightman314** [comment]
I believe I've found the issue. When I added the client-side trigger to reload the configs it also reloaded the server config, causing it to attempt to send a sync packet to the clients despite it being the client itself, which naturally caused an error during the login phase resulting in this softlock. I'll have a fix out asap to correct this :)

**Comment by Lightman314** [comment]
Fixed in v2.2.0.1d. Thank you for reporting!
