### ISSUE TITLE
BUG: Client crash when typing in Search Bar of vending machine for Barter tab

### ISSUE THREAD

**Issue by dylanjkl** [Lightman314/LightmansCurrency#182]
### Minecraft Version

1.20.1

### Forge Version

1.20.1-forge-47.1.96

### Lightman's Currency Version

1.20.1-2.2.0.1d

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

N/A (modlist: https://gist.github.com/dylanjkl/2014586020652426c8cb3695a0cf022d)

### Describe the bug

Client will initiate a disconnect and hard crash when typing in the Search Bar for items in a vending machines Barter tab.

### To Reproduce

1. Place Vending Machine
2. Put any item (I used Oak Boat)
3. Selling method set to Barter
4. Try and use the search feature to select an item to barter for (I tried to type Dirt and crashed before being able to finish the word)
5. Client crashes

### Screenshots/Logs/Crash Reports

[crash-2024-01-26_23.37.23-client.txt](https://github.com/Lightman314/LightmansCurrency/files/14070152/crash-2024-01-26_23.37.23-client.txt)

![image](https://github.com/Lightman314/LightmansCurrency/assets/25552125/6a173cd5-912c-46e0-915d-273f10c6309b)

**Comment by Lightman314** [comment]
Fixed in v2.2.0.1e
