### ISSUE TITLE
BUG: New villager trades back to emerald after upgrade

### ISSUE THREAD

**Issue by AnyankaT** [Lightman314/LightmansCurrency#184]
### Minecraft Version

1.20.1

### Forge Version

47.1.3

### Lightman's Currency Version

1.20.1-2.2.0.1e

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

Not sure? Don't think so

### Describe the bug

After updating from 1.20.1-2.1.2.4b on the weekend, Vanilla villagers have reverted to emeralds for trades. Their existing trades are in coin, but any new trades, or new villagers, are trading in emeralds. I've updated the config file to change the vanilla and modded villager trades, but I don't think it's reading it.

### To Reproduce

1. Updated to 1.20.1-2.2.0.1e
2. Upgrade a villager to a new trade, or spawn a new villager 
3. New trades are in emeralds rather than coins.

### Screenshots/Logs/Crash Reports

[lightmanscurrency-common.lcconfig.txt](https://github.com/Lightman314/LightmansCurrency/files/14076557/lightmanscurrency-common.lcconfig.txt)

**Comment by Lightman314** [comment]
Not doubting you, but you did reload the config after to edited it with the `/lcconfig reload` command correct? I'll take a looksie when I get home regardless, just to be safe, but I figured I'd ask just to be sure as the new config files will not reload automatically and some people might not be used to that.

**Comment by AnyankaT** [comment]
I rebooted the server at least twice, and have re-saved the config and reloaded it with a chat command at least once also.

**Comment by Lightman314** [comment]
Just double-checking. The server probably loads the villager trades before the configs are loaded, so I'll have to add some form of check or otherwise make sure the configs are loaded before said event happens.

**Comment by Lightman314** [comment]
Fixed in v2.2.0.1f. Thank you for reporting!
