### ISSUE TITLE
BUG: Notifications don't seem to work

### ISSUE THREAD

**Issue by gaboemi** [Lightman314/LightmansCurrency#187]
### Minecraft Version

1.20.1

### Forge Version

Forge 1.20.1 47.2.1

### Lightman's Currency Version

2.2.0.1e

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

Notifications dont fire when a trade has been performed, also doesnt leave a log in the trade log

### To Reproduce

1. Setup notifications
2. Wait to have someone to trade something

### Screenshots/Logs/Crash Reports

![imagen](https://github.com/Lightman314/LightmansCurrency/assets/57926365/d18622d9-4da1-4c5f-9729-52b18eabd9da)

**Comment by Lightman314** [comment]
Fixed in 2.2.0.3a. Thank you for reporting.
