### ISSUE TITLE
BUG: Teams doesnt add members correctly

### ISSUE THREAD

**Issue by gaboemi** [Lightman314/LightmansCurrency#188]
### Minecraft Version

1.20.1

### Forge Version

Forge 1.20.1 47.2.1

### Lightman's Currency Version

2.2.0.1e

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

Doesnt add member to the team succesfully, it seems to add it to the member list but it doesnt appear he has access to the team account or menu
Note the member which i tried to add has his name in all caps, maybe that influences the error, as when i added someone with lowercase it seem to work fine

### To Reproduce

1. Create a team
2. Add a member to a team

### Screenshots/Logs/Crash Reports

![imagen](https://github.com/Lightman314/LightmansCurrency/assets/57926365/ecb1432a-7992-4c10-9bc4-a54c96df7250)
![imagen](https://github.com/Lightman314/LightmansCurrency/assets/57926365/9199c2db-f38d-431d-8afb-fa8d3897a7a6)

**Comment by Lightman314** [comment]
The input case shouldn't matter, as it will automatically correct the name when it locates its matching profile (same as done by the vanilla whitelist/ban commands). If they can't access the team regardless then either you put a typo in the name somewhere and found a different player with a similar name, or somehow their UUID got messed up somehow...

**Comment by gaboemi** [comment]
Mmmh i dont seem to have done a typo, also curiosly i dont seem to be able to remove my friend from the group

**Comment by Lightman314** [comment]
Just to be certain, but your server doesn't have `online_mode` disabled in the server.properties does it?

**Comment by Lightman314** [comment]
Unable to replicate, and no response received in over 2 weeks. Closing issue.
