### ISSUE TITLE
BUG: Wallet no longer equippable in Curios slot

### ISSUE THREAD

**Issue by YoshiNoodles** [Lightman314/LightmansCurrency#192]
### Minecraft Version

1.19.2

### Forge Version

43.3.0

### Lightman's Currency Version

2.2.0.3a

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

CuriosAPI v5.1.6.1

### Describe the bug

It used to be that you could equip the Wallet in a Curios slot, but as of the latest update, that doesn't exist anymore

### To Reproduce

1. Open a singleplayer world
2. Obtain a wallet
3. Open Curios menu
4. Find there's no longer a Curios slot for the wallet

### Screenshots/Logs/Crash Reports

![2024-02-08_22 25 08](https://github.com/Lightman314/LightmansCurrency/assets/43329750/9cd08932-d3e3-4f79-9d0b-a73b00d647d4)
![2024-02-08_22 25 14](https://github.com/Lightman314/LightmansCurrency/assets/43329750/a51a94f1-384f-4de2-8ac3-dc90c9d802ba)

**Comment by ChangeOtaku** [comment]
confirm this is hapening in 1.19.2 (forge 43.3.0)

**Comment by ChangeOtaku** [comment]
used /reload and the slot appeared
![image](https://github.com/Lightman314/LightmansCurrency/assets/40974662/7341480a-b9b3-4439-a228-9f7f17a5a998)

**Comment by ChangeOtaku** [comment]
oh, got it... it disappears when Curios menu is open
![image](https://github.com/Lightman314/LightmansCurrency/assets/40974662/7eb82369-dac7-4767-95d0-faa106162bb2)

**Comment by Lightman314** [comment]
Fixed in v2.2.0.3b. Thank you for reporting.
