### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by EvilDragonKing** [Lightman314/LightmansCurrency#194]
### Minecraft Version

1.20.1

### Forge Version

47.1.84

### Lightman's Currency Version

1.20.1-2.2.0.3a

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

none

### Describe the bug

when i edit the mastercoin.json when i try to change the displayType to lightmanscurrency:number i do not get the other inputs. the wiki keeps tellling me
about i try to add it my self but it dosn't like it.

### To Reproduce

1 open mastercoin.json
2 edit the display type to lightmanscurrency:number
3 while in game type in lcconfig reload
4 reopen mastercoin.json

### Screenshots/Logs/Crash Reports

[MasterCoinList.json](https://github.com/Lightman314/LightmansCurrency/files/14228774/MasterCoinList.json)

**Comment by Lightman314** [comment]
You are missing the required `displayFormat` and `baseUnit` values. Please read the wiki section thoroughly & check your logs for errors before reporting these as an issue.

https://github.com/Lightman314/LightmansCurrency/wiki/Master-Coin-List-Config#number-display
