### ISSUE TITLE
BUG:  [Render thread/ERROR]: Error occurred while rendering wallet overlay! IWalletHandler

### ISSUE THREAD

**Issue by Krimatoria** [Lightman314/LightmansCurrency#196]
### Minecraft Version

1.19.2

### Forge Version

Forge 43.3.5

### Lightman's Currency Version

lightmanscurrency-1.19.2-2.2.0.3b.jar

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

Log Spam Again

### To Reproduce

lightmanscurrency-1.19.2-2.2.0.3b.jar

### Screenshots/Logs/Crash Reports

[17:54:34] [Render thread/ERROR]: Error occurred while rendering wallet overlay!
--
8132 | java.lang.NullPointerException: Cannot invoke "io.github.lightman314.lightmanscurrency.common.capability.wallet.IWalletHandler.getWallet()" because "walletHandler" is null
8133 | at io.github.lightman314.lightmanscurrency.client.gui.overlay.WalletDisplayOverlay.render(WalletDisplayOverlay.java:52) ~[lightmanscurrency-1.19.2-2.2.0.3b.jar%23593!/:1.19.2-2.2.0.3b]
8134 | at net.minecraftforge.client.gui.overlay.ForgeGui.lambda$render$0(ForgeGui.java:141) ~[forge-1.19.2-43.3.5-universal.jar%23724!/:?]
8135 | at net.minecraftforge.client.gui.overlay.ForgeGui.mda78bda$lambda$batching$0$0(ForgeGui.java:1265) ~[forge-1.19.2-43.3.5-universal.jar%23724!/:?]
8136 | at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%23121!/:?]
8137 | at net.minecraftforge.client.gui.overlay.ForgeGui.redirect$dae000$batching(ForgeGui.java:1259) ~[forge-1.19.2-43.3.5-universal.jar%23724!/:?]
8138 | at net.minecraftforge.client.gui.overlay.ForgeGui.m_93030_(ForgeGui.java:136) ~[forge-1.19.2-43.3.5-universal.jar%23724!/:?]
8139 | at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:876) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
8140 | at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
8141 | at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
8142 | at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
8143 | at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23719!/:?]
8144 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
8145 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
8146 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
8147 | at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
8148 | at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23101!/:?]
8149 | at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?]
8150 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?]
8151 | at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?]
8152 | at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?]
8153 | at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?]
8154 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?]
8155 | at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?]
8156 | at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]

**Comment by Lightman314** [comment]
Fixed in v2.2.0.3c. Thank you for reporting!

**Comment by Krimatoria** [comment]
> Исправлено в версии 2.2.0.3c. Спасибо за отчет!

Nice)))

**Comment by Krimatoria** [comment]
> Исправлено в версии 2.2.0.3c. Спасибо за отчет!

Ооо так можно было по русски писать?)
