### ISSUE TITLE
Coins and biological spoils falling simultaneously

### ISSUE THREAD

**Issue by qiantu1** [Lightman314/LightmansCurrency#198]
Sorry to trouble the author.
Minecraft Version
1.20.1

Forge Version
Forge 43.3.5

Lightman's Currency Version
lightmanscurrency-1.20.1-2.1.2.4b.jar

Environment Type
Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

Other relevant Mods
No response

Describe the bug
No solution found in the wiki.Coins and biological spoils cannot fall at the same time. The configuration has been changed and all biological spoils have been replaced with coins, but the original biological spoils disappeared. Is there a way to have both.

To Reproduce
lightmanscurrency-1.20.1-2.1.2.4b.jar

**Comment by Lightman314** [comment]
The coin drops do not in any way affect the default item drops, and during testing the mobs have dropped their default drops (usually tested on zombies, so rotten flesh, etc.) at the same time as the dropped coins... If this is not happening for you then another mod must be messing with the entity death event, and/or you're just getting some really weird RNG.
