### ISSUE TITLE
[Crash] Mod crashing on server loadup

### ISSUE THREAD

**Issue by dreckz** [Lightman314/LightmansCurrency#2]
Server crashes during loadup
Mod Version: 3.3.4

Crashlog:
[crash-2021-09-16_15.49.57-fml.txt](https://github.com/Lightman314/LightmansCurrency/files/7179262/crash-2021-09-16_15.49.57-fml.txt)

**Comment by Lightman314** [comment]
I have to ask, what do you mean by "Mod Version: 3.3.4", cause that is neither the forge version, not the lightmans currency version.

Either way, will be fixed for version 1.16.4-0.8.3.5. Friggin client-side only functions are the death of me... :(
