### ISSUE TITLE
BUG: Making a currency list over 6 coins wont render anything below the top 6

### ISSUE THREAD

**Issue by ChaosDogG** [Lightman314/LightmansCurrency#201]
### Minecraft Version

1.20.1

### Forge Version

47.1.99

### Lightman's Currency Version

2.2.1.0a

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

Thermal Series, Create Deco

### Describe the bug

When I set up the coins from other mods like Thermal and Create Deco, the coins are registered and work as expected in both the wallet, the ATM, and trading blocks, but actually rendering coins below the top 6 wont actually render within trade menus or the ATM

### To Reproduce

1. Install mod with Thermal Series and Create Deco
2. Fill out MasterCoinList with custom coins
3. Reload config
4. Go to ATM and go to tab with coins
5. Witness the issue

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrency/files/14349860/latest.log)

**Comment by Lightman314** [comment]
Widget was calculating the max scroll incorrectly, causing it to hide the scroll buttons. Will be fixed soon.

**Comment by ChaosDogG** [comment]
awesome! keep up the great work!
