### ISSUE TITLE
BUG: TPS Money 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [Lightman314/LightmansCurrency#202]
### Minecraft Version

1.19.2

### Forge Version

Forge 43.3.5

### Lightman's Currency Version

lightmanscurrency-1.19.2-2.2.1.0b.jar

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

Placebo-1.19.2-7.3.5.jar
Quark-3.4-418.jar
Raided-1.19.2-0.1.4.jar
RegionsUnexploredForge-0.5.3+1.19.2.jar
rhino-forge-1902.2.3-build.284.jar
rottencreatures-forge-1.19.2-1.0.1.jar
rubidium-extra-0.4.19+mc1.19.2-build.105.jar
sons-of-sins-1.19.2-2.1.5b.jar
spark-1.10.37-forge.jar
spore_1.19_2_2.0.2c.jar
superbosses-1.2.0-1.19.2.jar
Supernatural-2.6.5.jar
TenebrousLands_1.19.2.jar
teraphobia-2.0.0.jar
TerraBlender-forge-1.19.2-2.0.1.166.jar
Terralith_1.19.3_v2.3.12.jar
textrues_embeddium_options-0.1.1+mc1.19.2.jar
The_Graveyard_2.5.3_(FORGE)_for_1.19.2..jar
The_Graveyard_Biomes_1.4_(FORGE)_for_1.19.2.jar
thefallenmonstersprehistoricaupdate.jar
The-Hordes-1.19.2-1.2.3.jar
There is something in the caves_1.0.0.jar
UndeadUnleashed-1.1.1-1.19.2.jar
yeetusexperimentus-1.0.1-build.2+mc1.19.1.jar
YungsApi-1.19.2-Forge-3.8.10.jar
zombieawareness-1.19.2-1.12.3.jar
aether-1.19.2-1.2.0-forge.jar
architectury-6.5.90-forge.jar
Atlas-Lib-1.19.2-1.1.6.jar
AutoRegLib-1.8.2-55.jar
BadOptimizations-1.6.3.jar
BOH_0.0.2.5.jar
born_in_chaos_[Forge]1.19.2_1.10.1.jar
catalogue-1.7.0-1.19.2.jar
citadel-2.1.4-1.19.jar
configured-2.1.1-1.19.2.jar
Controlling-forge-1.19.2-10.0+7.jar
coroutil-forge-1.19.2-1.3.6.jar
cultofthewither2.4.jar
cumulus_menus-1.19.2-1.0.0-forge.jar
curios-forge-1.19.2-5.1.6.1.jar
Dangers in the Darkness_1.0.28_Forge_1.19.2.jar
darktimer-forge-1.19.2-1.1.5.jar
DistantFriends-1.19.2-0.2.3.jar
embeddium-0.3.5+mc1.19.2.jar
embeddiumplus-1.19.2-v1.2.4.jar
emi-1.1.2+1.19.2+forge.jar
endofherobrine-1.19.2-1.0.7.1.jar
EnhancedAI-1.8.5-mc1.19.2.jar
entityculling-forge-1.6.1-mc1.19.2.jar
FastFurnace-1.19.2-7.0.0.jar
Fastload-Reforged-mc1.19.2-3.4.0.jar
FastSuite-1.19.2-4.1.1.jar
FastWorkbench-1.19.2-7.1.4.jar
ferritecore-5.0.3-forge.jar
From-The-Fog-1.19-v1.9.1-Forge-Fabric.jar
geckolib-forge-1.19-3.1.40.jar
Icterine-forge-1.2.0.jar
ImmediatelyFast-Forge-1.2.10+1.19.2.jar
InsaneLib-1.7.5-mc1.19.2.jar
kotlinforforge-3.12.0-all.jar
kubejs-forge-1902.6.2-build.63.jar
L_Enders_Cataclysm-1.90 tongue fixed-1.19.2.jar
lazydfu-1.19-1.0.2.jar
lightmanscurrency-1.19.2-2.2.1.0b.jar
lootjs-forge-1.19.2-2.9.1.jar
MobCaptains-v2.1.2.jar
MobsPropertiesRandomness-4.2.3-mc1.19.2.jar
Monster Hunter Villager 1.1.0-1.19.2.jar
nerb-1.19.2-0.3-FORGE.jar
neruina-1.3.0-forge+1.18.2-1.20.1.jar
no_f3-1.0.jar
noisium-1.0.2.jar
observable-3.3.1.jar
Paxi-1.19.2-Forge-3.0.1.jar
Pehkui-3.7.11+1.19.2-forge.jar

### Describe the bug

Initially, I decided to rebuild my build of mods, adding several at a time and looking at what affects the TPS. Everything was fine, the difference was very small and he was stable anyway. 

Here are screenshots in the build of 77 mods out of 300. Impact on TPS before and after adding the Lightman's Currency mod

<details>
<summary> TPS - Take a look) </summary>

> Before adding the mod

![2024-02-26_17 06 56](https://github.com/Lightman314/LightmansCurrency/assets/106809386/9a041863-b373-4f5f-b12c-e18a6003c295)

> After adding the mod

![2024-02-26_17 10 21](https://github.com/Lightman314/LightmansCurrency/assets/106809386/114e6eeb-714a-4395-abc7-6bae18608480)

</details>

As soon as I added Lightman's Currency, I had a constant drawdown of TPS. I decided to go into Config and tried disabling each option individually and doing /reload to see the difference, but it was insignificant, drawdowns still persisted. Then I went to the Log file and saw there almost 10,000 messages [Skipping loading recipe] card_display  

<details>
<summary> Config</summary> 

![Screenshot_9](https://github.com/Lightman314/LightmansCurrency/assets/106809386/051f848d-3b88-4165-9e02-8e95e9514527)
![Screenshot_8](https://github.com/Lightman314/LightmansCurrency/assets/106809386/d08e7d83-e5dc-4231-b2ab-c1b2ccfe37eb)

  
</details>

<details>
<summary> 10.000 </summary> 

![image](https://github.com/Lightman314/LightmansCurrency/assets/106809386/18e9b6c8-ede9-4cc3-9f9c-c036f158b5b9)

  
</details>

> I don't think the reason is card_display.

The only thing that indicates TPS is the appearance of mobs. As soon as they are not there, there is no drawdown. Maybe it has something to do with coins?

![2024-02-26_18 58 04](https://github.com/Lightman314/LightmansCurrency/assets/106809386/5be299c9-e22e-44c6-96f7-6a2ee1a057b2)

> With mobs at day (You can see that when I removed the difficulty to peaceful and the mobs disappeared, the TPS became normal. This is interconnected with the mod and mobs, possibly a constant loot miscalculation.)

![2024-02-26_17 10 33](https://github.com/Lightman314/LightmansCurrency/assets/106809386/827bf5d9-96e5-4e6d-ad17-4f8ca121af00)
> Mobs at Night

### To Reproduce

1. Add lightmanscurrency-1.19.2-2.2.1.0b.jar
2. Create World 
3. ALT + F3 see TPS
4. Turn on the cheats and set the night, the difficulty mode is peaceful.
5. Look at the TPS it should be fine.
6. Turn on the normal difficulty without turning off the TPS display to see the difference.
7. Soon you will see permanent TPS bars in yellow, the more mods there are for mobs, the stronger the effect, as I understand it.

### Screenshots/Logs/Crash Reports

I have attached everything in the description of the problem.

**Comment by moninformateur** [comment]
I'm encountering the exact same issue on 1.20.1. It isn't immediately critical, but it certainly looks like some kind of leak on the server side. Since it's constant, it may have significant impact on the frame time of some server tasks like generating new chunks.

**Comment by Lightman314** [comment]
The most likely cause of it is the enchantment event ticks having more potential targets with more entities, as the coin magnet & money mending enchantments do *technically* work on non-players should they happen to somehow obtain an equipped wallet (which is not possible in base LC). I'll optimize it in the next update so that the enchantments only run on players since nobody seems interested in utilizing this feature though...

**Comment by Lightman314** [comment]
Should be fixed for 1.20.1 in v2.2.1.1.

Fix for 1.19.2 should hopefully be out within the week.

**Comment by Krimatoria** [comment]
> Должно быть исправлено для версии 1.20.1 в версии 2.2.1.1.
> 
> Исправление для 1.19.2, надеюсь, выйдет в течение недели.

I've already read it in your Discord) great) I'm already watching the update)  ❤️

**Comment by Lightman314** [comment]
2.2.1.1 has been backported to 1.19.2 :)
