### ISSUE TITLE
Feature Request:  Config update for villager buy/sell values

### ISSUE THREAD

**Issue by Br00t4L17y** [Lightman314/LightmansCurrency#204]
The problem:
We'd like to be able to assign a different tier of coin required to buy items from a villager, than the tier of coin received from selling. On a server where we limit the speed at which you obtain coins (coin mint disabled), we don't want players accruing coins too fast.

Proposed solution:
We'd like to make it so villagers sell items, say at T3 gold coin level. But then buy from the player at a T2 iron coin level. Being able to separate these values will help us fine tune the economy.

**Comment by Lightman314** [comment]
I was already going to modify the villager item configs based on another feature request/suggestion from my discord, so I'll go ahead and add this in there when I add that :)

**Comment by Br00t4L17y** [comment]
Awesome, thank you for the quick response. I am looking forward to it!

**Comment by Lightman314** [comment]
Appears to be working as intended:
![image](https://github.com/Lightman314/LightmansCurrency/assets/4554273/cb73c30a-58cb-4b3c-ad16-81fb1fb7c0a2)
Next build should be out soon:tm:, just need to do some more bug-testing before releasing it.

**Comment by Br00t4L17y** [comment]
Looks great! Will this be per trader? Or a global config option?

**Comment by Lightman314** [comment]
It will be both. The default replacement coin input can now have two items defined (seperated by a `;`, so a config option of "lightmanscurrency:coin_iron;lightmanscurrency:coin_copper" would result in the screenshotted results, and the villager overrides can have the same done to them as well (e.g. "minecraft:blacksmith-lightmanscurrency:coin_iron;lightmanscurrency:coin_copper", etc.)

This will now also be the default config value for the fletcher villager, buying items for copper coins but selling items to the players for iron coins, so you'll have an in-config example of how it's set up.

**Comment by Br00t4L17y** [comment]
Sounds perfect. Do you know when you will be releasing those changes?

**Comment by Lightman314** [comment]
If everything goes well I'm hoping to have this out tomorrow for 1.20.1, and hopefully have it backported to 1.19.2 within a week or so.

**Comment by Br00t4L17y** [comment]
Exciting, thanks for the quick turn around on this feature

**Comment by Lightman314** [comment]
Added in v2.2.1.1.
