### ISSUE TITLE
Feature Request: New Lapis Coin

### ISSUE THREAD

**Issue by mikes4b22** [Lightman314/LightmansCurrency#206]
**Is your feature request related to a problem? Please describe.**
I love the minting/melting feature but due to the farmability of gold and even emeralds, 1 diamond is only worth 10 emeralds or 100 gold. I don't mind diamonds and netherite being farmable through the conversion/transmuting process, but it should be expensive to do so.

**Describe the solution you'd like**
Is it possible to add in a Lapis Coin (or other alternative) between Emeralds and Diamonds in the chain or at least between Gold and Emeralds? This would make the conversion rate be 1 diamond = 10 lapis or 100 emeralds and 1 netherite = 10 diamonds or 100 lapis.

**Describe alternatives you've considered**
[Joins JE by DarkhaxDev](https://www.curseforge.com/minecraft/mc-mods/coins-je) had a similar implementation with Titanium coins at one point but overall just lacks all of the functionality of LC.

**Additional context**
I will probably end up modifying the recipes on my end to make getting the resources back through melting even more expensive (I want 1 pile/9 coins = 1 ingot/gem.) This makes downgrading to things like iron/copper have a "cost" as well so it isn't straight duping.

**Comment by Lightman314** [comment]
I have no plans on adding more coins to LC... You could easily make an addon mod that does this as all you'd strictly need to do is add a lapis coin item and then you just need to add the minting recipes (which you mentioned that you were already going to be editing these, so you can just plop it in with those) and edit the master coin list to slide it into the middle of the coin chain.
