### ISSUE TITLE
BUG:  "tax_block" area graphic display error.

### ISSUE THREAD

**Issue by QianMuu** [Lightman314/LightmansCurrency#208]
### Minecraft Version

1.19.2

### Forge Version

1.19.2

### Lightman's Currency Version

lightmanscurrency-1.19.2-2.1.2.4

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

I placed "tax_block" to display the red cube area, and when I removed the block, the cube area was still there.
Is there any way to solve this problem?

### To Reproduce

1. Place blocks
2. Destroy blocks
3. The square disappears and the red area disappears
4. Restart the server
5. The square disappears and the red area exists

### Screenshots/Logs/Crash Reports

![{95D7FED9-C86D-4e38-BCE7-BB0F9DAE3F23}](https://github.com/Lightman314/LightmansCurrency/assets/50398180/5966aa4d-622b-457c-80d2-0ea2d2b69597)

**Comment by Lightman314** [comment]
This issue was fixed in v2.2.0.3.
You will however still need to manually delete the tax collector in question after updating via the `/lcadmin taxes list` command (to find the tax collector ID), and the `/lcadmin taxes delete <taxCollectorID>` command.

**Comment by TrulyS1r0** [comment]
I myself am on v2.1.2.5, And those commands dont exist for me... so pleae help me too XD
