### ISSUE TITLE
Feature Request: {Trinkets Integration}

### ISSUE THREAD

**Issue by Dumpling00** [Lightman314/LightmansCurrency#212]
Hello! This is a bit of a situational request, but since Curios API isn't available on Fabric 1.20.1, would it be possible to make the wallet compatible with a trinkets slot? Maybe the leggings one so that it can still show attached to the belt?

The reason I ask this is because I'm running a bit of an adventure game with Switchy, where each player can have different character presets, and through some of its modules, it's possible to make things like health, inventory, exp, trinkets etc. unique to each character preset.
Right now, because the wallet is its own thing, each preset shares the same wallet. I'd like to make it so each character can have their own wallet.

Thank you for your consideration!

**Comment by Lightman314** [comment]
Please make feature requests for LC Fabric on the github page for that version of the mod (https://github.com/Lightman314/LightmansCurrencyFabric)

**Comment by Dumpling00** [comment]
> Please make feature requests for LC Fabric on the github page for that version of the mod (https://github.com/Lightman314/LightmansCurrencyFabric)

Done thank you so much!
