### ISSUE TITLE
BUG: FTB Chunks and Teams do not appear when Lightman's Currency is installed

### ISSUE THREAD

**Issue by ToxinZangoose** [Lightman314/LightmansCurrency#215]
### Minecraft Version

1.20.1

### Forge Version

47.2.21

### Lightman's Currency Version

2.2.1.2a

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

Not exactly a crash, but just incompatibility with FTB Chunks and Teams. 

The map disappears when LC's is installed and the keybinds for the world map don't work. This issue was only resolved by removing the Currency mod, which had a GUI error when used with FTB Chunks. 

I want to use this mod badly, but not being able to claim chunks, view the map, or see players on my team made the server remove it. 

Please take this into consideration, I would love to have a functioning economy on a server with player trading.

### Describe the bug

The bug is related to the GUI with FTB Chunks and Teams, while LC is installed, it refuses to load the map or even display it on client side. The keybinds to open the world map also have broken when it is installed too.

### To Reproduce

1. Start a server with Lightman's Currency and FTB Chunks and Teams installed.
2. Boot up the server.
3. Join server and see minimap missing and the keybinds for the world map broken.

### Screenshots/Logs/Crash Reports

I am not the server owner and I doubt he would allow me to paste his info on here without permission.
I do have the debug log on my side, however.
https://mclo.gs/iXli0Mp

**Comment by Lightman314** [comment]
Are you certain that your server owner hasn't disabled the minimap and/or world map server-side, as I'm fairly certain that is something FTB Chunks allows server owners to do. I played on a server once that had the FTB Chunks minimap forcibly disabled as we were using another minimap mod...

On another note, my mod literally doesn't interact with the minimap and/or world map at all, it only accesses the bonus claims/forceload data whenever a command is run, so it's literally impossible for my mod to be the cause of this. I mean, the key-binds could *technically* become a conflict, but only if the world-map keybind is set to the same key as one of my mods key-binds...

**Comment by Lightman314** [comment]
Just for grins, I double-checked everything on my test server with the latest LC, FTB Chunks, Teams, etc. for 1.20.1 and when I joined my test server I was able to open the world map with no issues. As such, I am officially unable to replicate the issue.

**Comment by Lightman314** [comment]
A suggestion from a friend:
He recommends removing embeddium as that sodium branch is unstable and could easily be the cause of issues like these.

**Comment by ToxinZangoose** [comment]
Thank you for your time, I appreciate the quick response. I’ll let the server owner know.
