### ISSUE TITLE
BUG: Game Crash On Survival Inventory Opened In Creative

### ISSUE THREAD

**Issue by IDKhowtodothings38** [Lightman314/LightmansCurrency#216]
### Minecraft Version

1.19.2

### Forge Version

43.3.8 & 43.3.0

### Lightman's Currency Version

2.2.1.3a

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

Roughly Enough Items
Embeddium

### Describe the bug

If you are in Creative Mode and try to open the survival mode tab, you crash due to a slot error. If you open the inventory in survival mode, it will work fine. "java.lang.IllegalAccessError: Update to non-static final field net.minecraft.world.inventory.Slot.f_40220_ attempted from a different method (setX) than the initializer method <init>"

### To Reproduce

1. Go Into Creative
2. Open Survival Mode Tab

### Screenshots/Logs/Crash Reports

[crash-2024-04-08_15.22.23-client.txt](https://github.com/Lightman314/LightmansCurrency/files/14910663/crash-2024-04-08_15.22.23-client.txt)

**Comment by Lightman314** [comment]
I'll look into this, as this shouldn't be happening and 100% is NOT happening in the 1.20.1 version despite having the exact same code for this...

**Comment by Lightman314** [comment]
Fixed in v2.2.1.3b. Thank you for reporting.
