### ISSUE TITLE
Feature Request: Is it possible to increase the time of "paygate"?

### ISSUE THREAD

**Issue by QianMuu** [Lightman314/LightmansCurrency#217]
The maximum time now is one minute, which I found as I was working on it that might not be enough for me.
So can we add more, one minute, three minutes, five minutes, ten minutes.？

**Comment by Lightman314** [comment]
This should be reasonable. I'll add a `paygate.maxRedstoneDuration` config option to the server config so that you can customize the maximum tick duration for paygates :)
