### ISSUE TITLE
BUG: Slot Machine show tooltip of possible result in main menu

### ISSUE THREAD

**Issue by Dowar** [Lightman314/LightmansCurrency#223]
### Minecraft Version

1.20.1

### Forge Version

47.2.32

### Lightman's Currency Version

2.2.1.3b

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

When you mouse is at the position of any item of the possible results menu the tooltip appear (even when your not in the possible results menu)

### To Reproduce

1. Place a slot machine and open the menu
2. Go to the Edit Entries menu and set an entry
3. Return to main menu
4. Click the “click to see possible results” buttons
5. Look at the location of the item and remember it
6. Return to main menu
7. Move the mouse to the position where the item was in the "possible results" menu, it should show the tooltip even if you are in the wrong menu.

### Screenshots/Logs/Crash Reports

![Capture d'écran 2024-05-22 005743](https://github.com/Lightman314/LightmansCurrency/assets/34864915/9426cac6-09c9-4286-b066-b708646e3cd9)

![Capture d'écran 2024-05-22 005726](https://github.com/Lightman314/LightmansCurrency/assets/34864915/0f989cb9-f809-4395-adcc-6335e6870188)

**Comment by Lightman314** [comment]
So it does. I'll make sure to fix this in the next update :)
