### ISSUE TITLE
BUG: Fluid tap scrollbar in set price menu

### ISSUE THREAD

**Issue by Dowar** [Lightman314/LightmansCurrency#224]
### Minecraft Version

1.20.1

### Forge Version

47.2.32

### Lightman's Currency Version

2.2.1.3b

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

LC Tech 0.2.1.3c

### Describe the bug

When you configure the price of a liquid in the "fluid tap", the scroll bar of the menu to configure the fluid is displayed

### To Reproduce

1. Place a fluid tap
2. Open the edit trade menu
3. Clic on set price button to create a trade
4. Scrollbar is visible even if it not in the set fluid menu

### Screenshots/Logs/Crash Reports

![Capture d'écran 2024-05-22 171049](https://github.com/Lightman314/LightmansCurrency/assets/34864915/81be9351-df42-4fd7-a9da-787559212a7d)

**Comment by Lightman314** [comment]
Technically an LC Tech bug, but I'll make sure to fix that in the next LC Tech update, as it's definitely gonna need one after the upcoming LC update.

**Comment by Lightman314** [comment]
Fixed in LC Tech v0.2.1.4a
