### ISSUE TITLE
BUG: Ticket Kiosk will show a No Stock warning, even though the trade is for a printed ticket.

### ISSUE THREAD

**Issue by ConnorNMoran** [Lightman314/LightmansCurrency#225]
### Minecraft Version

1.20.1

### Forge Version

47.2.32

### Lightman's Currency Version

1.20.1-2.2.1.3b

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

When using a ticket kiosk, it seems that after putting money into the kiosk, I can select the ticket to be printed for the amount required, and it will work, but it will show a No Stock warning over the arrow, which is confusing.

### To Reproduce

1. Place a Ticket Kiosk.
2. Set up a trade - Type: Sale - 1 gold coin for 1 ticket.
3. Attempt to buy the ticket.
4. View the warning over the arrow.

### Screenshots/Logs/Crash Reports

![Ticket Kiosk Bug](https://github.com/Lightman314/LightmansCurrency/assets/45665263/6cc9aefe-5e7f-48c9-8880-61880d2fd40c)

**Comment by ConnorNMoran** [comment]
Oddly, doesn't occur any more after messing with the ticket names? I'm unsure what fixed it.

**Comment by Dowar** [comment]
It's because of [this](https://github.com/Lightman314/LightmansCurrency/issues/222)
Basically, you are not supposed to be able to buy a ticket without materials (paper) in stock (because the kiosk need to craft the ticket)

**Comment by Lightman314** [comment]
Indeed. This is a duplicate issue of #222. Please refer to that issue report for all future communications.
