### ISSUE TITLE
BUG: Invalid Playerdata after Update

### ISSUE THREAD

**Issue by shinei01** [Lightman314/LightmansCurrency#230]
### Minecraft Version

1.20.1

### Forge Version

47.3.1

### Lightman's Currency Version

1.20.1-2.2.2.0

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

After updating to the latest version, it wasn't possible to join the server again in reason of invalid playerdata. After going back to the Version before it was possible to join the server again.

### To Reproduce

1. Have a server with playerdata already
2. Update to latest version
3.  Try to connect to the server
4. Go back to previous version
5. Try to connect to the server again

### Screenshots/Logs/Crash Reports

I'm afraid there is no log for any help.

**Comment by Lightman314** [comment]
There is always a log that can help. The latest.log & debug.log files will always be generated within the logs folder no matter what happens, and will typically contain useful information about the issue.

**Comment by Lightman314** [comment]
Update: Just for grins, I updated my test client/server to this version and I was able to connect with no issues. I'm hereby flagging this issue as "unable to replicate" until such a time as you provide me with the requested log files.

**Comment by shinei01** [comment]
[debug.log](https://github.com/user-attachments/files/15754105/debug.log)

here's the debuglog

**Comment by Lightman314** [comment]
Thank you for the logs. Should be fixed in v2.2.2.0a :)
