### ISSUE TITLE
BUG: Crash when a trader is broken while another player is in a GUI

### ISSUE THREAD

**Issue by FoxMcloud5655** [Lightman314/LightmansCurrency#231]
### Minecraft Version

1.20.1

### Forge Version

47.2.20

### Lightman's Currency Version

2.2.2.0

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

When a player is interacting with anything from Lightman's Currency and has a GUI open, if the block they're interacting with is broken (i.e. by the owning player), the client with the GUI open crashes.

Probably can be fixed pretty easily by performing a null check on the supplier, and if null, closing the GUI.

### To Reproduce

1. Place down a block with a GUI from Lightman's Currency (Pay Gate, Display Case, etc.)
2. Have another player open the GUI.
3. Break the block.
4. Observe as the other player crashes.

### Screenshots/Logs/Crash Reports

[crash-2024-06-10_09.23.39-client.txt](https://github.com/user-attachments/files/15774968/crash-2024-06-10_09.23.39-client.txt)

**Comment by Lightman314** [comment]
Should be fixed in v2.2.2.0b
