### ISSUE TITLE
BUG: cash register "not linked" message doesn't appear properly

### ISSUE THREAD

**Issue by MikeyPantsOn** [Lightman314/LightmansCurrency#233]
### Minecraft Version

1.20.1

### Forge Version

47.2.20

### Lightman's Currency Version

1.20.1-2.2.2.1

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

cash register "not linked" message doesn't appear properly 
#232 

### To Reproduce

1.right click a cash register which isn't linked

### Screenshots/Logs/Crash Reports

![Screenshot 2024-06-16 223839](https://github.com/Lightman314/LightmansCurrency/assets/29602024/1791cefb-b6b3-441a-8144-192b02e8387d)

**Comment by Lightman314** [comment]
Fixed in v2.2.2.1a. Thank you for reporting.
