### ISSUE TITLE
BUG: Can't start minecraft

### ISSUE THREAD

**Issue by insprat** [Lightman314/LightmansCurrency#234]
### Minecraft Version

1.19.4

### Forge Version

45.3.0

### Lightman's Currency Version

2.1.2.4a

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

Everytime i try to load the game it does NOT work. It js crashes i can't even open the game while it's in mods list. I tried to run it with a mod pack it didn't work yet i tried to run the mod ON ITS OWN it didn't work again

### Describe the bug

Put the mod in mods file
Try to run the game

### To Reproduce

I have no idea

### Screenshots/Logs/Crash Reports

![image](https://github.com/Lightman314/LightmansCurrency/assets/94718624/06ed8602-984a-4e9f-bf66-cb6023a52b11)
[crash-2024-07-06_17.02.20-client.txt](https://github.com/user-attachments/files/16116399/crash-2024-07-06_17.02.20-client.txt)

**Comment by Lightman314** [comment]
Should be fixed in LC 1.19.4-2.1.2.4b
