### ISSUE TITLE
BUG: 'General' Button does not work 

### ISSUE THREAD

**Issue by Pyrael123** [Lightman314/LightmansCurrency#236]
### Minecraft Version

1.20.1

### Forge Version

47.3.5

### Lightman's Currency Version

2.2.2.3

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

Clicking the "General" button does not bring me back to my inventory, when it was supposed to do so, slight QoL improvement

### To Reproduce

1. Open Inventory
2. Click on the "Notification" button
3. Click on "General" button

### Screenshots/Logs/Crash Reports

![image](https://github.com/user-attachments/assets/19276ef7-3b8a-498d-9ae3-61ad1d4275ff)

**Comment by Lightman314** [comment]
The "General" button never has and never will return you to your inventory. In the notification screen, the "General" tab displays all notifications regardless of category, while other tabs will appear as needed to display notifications from specific sources.
