### ISSUE TITLE
BUG: Personal account is not created. : "ERROR FINDING ACCOUNT"

### ISSUE THREAD

**Issue by KimDongCHAAAN** [Lightman314/LightmansCurrency#237]
### Minecraft Version

1.21

### Forge Version

neoforge 21.0.80

### Lightman's Currency Version

2.2.2.4b

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

in multiplay, Personal accounts are not created. Team accounts are only created, but currency transactions are not allowed.

### To Reproduce

Even if I create a new server and test it, the same issue occurs.

### Screenshots/Logs/Crash Reports

<img width="726" alt="issue1" src="https://github.com/user-attachments/assets/489ad924-456e-4301-b3bd-fb362e3c8428">
<img width="1000" alt="issue2" src="https://github.com/user-attachments/assets/a2a425ba-ad81-40c2-9bd3-01df9ca6e28d">

**Comment by Lightman314** [comment]
Fixed in v2.2.2.4c
