### ISSUE TITLE
Feature Request: {How to manage my 'chocolate coins' in ATM without using the'/lcadmin toggleadmin 'command}

### ISSUE THREAD

**Issue by ikeyaswing** [Lightman314/LightmansCurrency#239]
Hello！is there any way to use this interface even in non administrator mode
![2024-07-18 093529](https://github.com/user-attachments/assets/3bfbdc4b-1527-4c36-b767-c5ca6885cc1e)

**Comment by Lightman314** [comment]
You'll unlock that by having any chocolate coin in your inventory (or by running `/lcadmin events <player> chocolate_coins` to manually unlock them for the given player).

Also this is a _question_, not a feature request, and thus should **NOT** be made on github. Please refer to the Discord Link in my mods description (or the comments section if you use curseforge) to ask questions in the future.

One thing I will note is that there is a slight desync issue in LC for 1.21, so you'll need to update to v2.2.2.4d to fix this, as previously it didn't resync the data when changed or when changing dimensions, so if this caused any confusion I do apologize.
