### ISSUE TITLE
BUG: 1.20.1 Issue Connecting to Server. Internal Exception 

### ISSUE THREAD

**Issue by Zelioth** [Lightman314/LightmansCurrency#241]
### Minecraft Version

1.20.1

### Forge Version

47.3.5

### Lightman's Currency Version

2.2.2.6

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

[Friends United] SilverLeaf Cottage Core.
https://www.curseforge.com/minecraft/modpacks/silverleaf-cottage-core-friends-united

### Describe the bug

We are testing an update for our 1.20.1 pack and in the most recent version we added "Lightmans Currency". This bug doesn't affect Single Player but seems to affect clients connecting to server. 

The issue is fixed by removing Lightmans Currency. 

### To Reproduce

1. Contain the same mods in version 0.0.9 of SilverLeaf Cottage Core
2. Add Lightmans Currency. 
3 Create a forge server with most recent version
4 Start and attempt to connect. 

### Screenshots/Logs/Crash Reports

[debug.log](https://github.com/user-attachments/files/16436765/debug.log)
[latest.log](https://github.com/user-attachments/files/16436766/latest.log)
![image](https://github.com/user-attachments/assets/8c6c5768-c661-4278-a8ef-a3a8403b24e1)

**Comment by Lightman314** [comment]
I'm afraid I need the logs from the client, not the server as the issue is happening on the client itself (and it's simply telling the server what error it got as the disconnect reason without giving any actually useful info such as the stacktrace, etc.)

**Comment by Lightman314** [comment]
If no response with the requested logs is received by Wednesday I'm afraid I'll be forced to close the issue as I'm unable to replicate the issue, and the server logs do not have any information on the error that's causing problems on the client.

**Comment by Lightman314** [comment]
As no response has been made to provide the required information, and I am unable to replicate this issue in a test environment (or more accurately a friends 1.20.1 server that contains my mod) I'm afraid I have to close this issue. Feel free to re-open when you can provide the client-side logs I've requested so that I can actually look into the issue.
