### ISSUE TITLE
BUG:  Team Setup closing

### ISSUE THREAD

**Issue by shinei01** [Lightman314/LightmansCurrency#242]
### Minecraft Version

1.20.1

### Forge Version

47.3.5

### Lightman's Currency Version

1.20.1-2.2.3.0a

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

While giving a name to a team which contains an E and typing it the Menu will close.

### To Reproduce

Setup new team
Give the team a name with an E (e.g. horse)

### Screenshots/Logs/Crash Reports

bug isn't found in any log

**Comment by Lightman314** [comment]
Will be fixed in the next update. Until then though, you can create your new team with a temporary name that doesn't include `e` in it (i.e. hors) and then re-name the team from the Team's Name tab which will **not** close when you hit the `e` button

**Comment by Lightman314** [comment]
Fixed in v2.2.3.1. Thank you for reporting :)
