### ISSUE TITLE
[Feature Request]: Show the Open Wallet keybind on the tooltip

### ISSUE THREAD

**Issue by CelestialAbyss** [Lightman314/LightmansCurrency#243]
**Is your feature request related to a problem? Please describe.**
One of my modpack players asked what the key bind was to open their wallet when I realized it doesn't show the key bind on the tooltip like other mods by default. I know players can check their key binds in the settings, but it helps *a lot* when it is visible first and foremost on a tooltip on cursor hover.

**Describe the solution you'd like**
Implement another line to the tooltip that shows the player's current keybind like other mods and wherever else it may be applicable.

---

Just for tracking purposes on your end ^-^

**Comment by Lightman314** [comment]
Added in v2.2.3.1
