### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by KevinGlitch** [Lightman314/LightmansCurrency#244]
### Minecraft Version

1.20.1

### Forge Version

47.3.5

### Lightman's Currency Version

2.2.3.0a

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

No other mods seem to be of cause, at least to my knowledge.

### Describe the bug

To my knowledge, setting an item on any market stall with a "free sample" causes the game to bug out when you enter the editor for that machine as either an owner or an admin. The only way to solve this bug is to replace the machine.

### To Reproduce

Create a market of any kind.
Create a selling option for anything at any cost
Set the shop to offer free samples
Close and open the editor
Game consistently crashes

### Screenshots/Logs/Crash Reports

[crash-2024-08-14_15.02.53-client.txt](https://github.com/user-attachments/files/16617771/crash-2024-08-14_15.02.53-client.txt)

**Comment by Lightman314** [comment]
Fixed in v2.2.3.1. Thank you for reporting :)
