### ISSUE TITLE
BUG: code 1

### ISSUE THREAD

**Issue by matirus1** [Lightman314/LightmansCurrency#246]
### Minecraft Version

1.20.1

### Forge Version

47.3.5

### Lightman's Currency Version

2.2.3.1

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

https://legacy.curseforge.com/minecraft/modpacks/husaria/relations/dependencies

### Describe the bug

nofing just code 1

### To Reproduce

the movie shows

### Screenshots/Logs/Crash Reports

https://www.youtube.com/watch?v=88z2CLhzqHo

**Comment by Lightman314** [comment]
Please attach the `latest.log` file from your installations `logs` directory and/or the crash report that was generated when the game crashed. The video provided does not in any way help me locate and resolve the issue, and could have been replaced with a simple statement of "the game crashes when booting/starting" or something similar.

**Comment by matirus1** [comment]
> Please attach the `latest.log` file from your installations `logs` directory and/or the crash report that was generated when the game crashed. The video provided does not in any way help me locate and resolve the issue, and could have been replaced with a simple statement of "the game crashes when booting/starting" or something similar.

 no log has any error and even the crash log has nothing but shows this code 1

**Comment by Lightman314** [comment]
Well considering that error codes aren't a thing in minecraft (it's at best a generic code to tell the launcher that something happened, not what actually happened) I can promise you that if you attached the logs and/or crash report it would include a **lot** more information than just a generic error code that means literally nothing. At the absolute minimum it will include the stack trace from whence the crash originated, which tells me what code was being run when the crash occurred. If your crash report does not include a stack trace then you're looking in the wrong place.

**Comment by matirus1** [comment]
[2024-08-16-6.log](https://github.com/user-attachments/files/16642482/2024-08-16-6.log)
![Zrzut ekranu (129)](https://github.com/user-attachments/assets/8174f58e-41cd-41f9-9f60-8f8d551e71e6)

**Comment by Lightman314** [comment]
The logs provided state that `lightmanscurrency-1.20.1-2.2.3.0a.jar` was loaded in that instance, not the 2.2.3.1 version you're claiming has the issue.
Fortunately (or unfortunately I suppose) someone else on my discord is having the same issue and was able to provide the correct logs that actually tell me where the issue is.
I'll have a patch soon to fix this issue.

**Comment by Lightman314** [comment]
Since this was a compile error, not a code error, the file has been re-uploaded with the same version number, but I have tested outside of the dev environment and confirmed that it is now working as intended.
