### ISSUE TITLE
BUG: Format error

### ISSUE THREAD

**Issue by JIAFALSEDREAM** [Lightman314/LightmansCurrency#248]
### Minecraft Version

1.20.1

### Forge Version

37.3.10

### Lightman's Currency Version

2.2.3.1

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

zh_cn file format is wrong
There is an extra space on line 1303

### To Reproduce

Get a wallet

### Screenshots/Logs/Crash Reports

![image](https://github.com/user-attachments/assets/58b85845-9320-4f2f-980c-d3a4c794244d)

**Comment by Lightman314** [comment]
I'll make sure to fix it in the next update. I do appreciate your thoroughness in providing the exact line number as well, made it really easy to find and fix the typo :)

**Comment by Lightman314** [comment]
Fixed for 1.21 in v2.2.3.2. Fix will be included in the 1.20.1 backport of said version.
