### ISSUE TITLE
BUG: Can't change CanMelt in Config.

### ISSUE THREAD

**Issue by GroovieSmoothie** [Lightman314/LightmansCurrency#249]
### Minecraft Version

1.20.1

### Forge Version

47.3.5

### Lightman's Currency Version

2.2.3.2

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

Currently, the bug is that A. The config files are .llconfig and not .toml, and always create a .llconfig file, AND that the "CanMelt", even if set to true, displays it as false, and therefore cannot melt. The only way I can alter the config is changing the config from .llconfig to .toml and back. In the config file and the most recent log, the "Option coin_mint.recipes.melt.[material] was missing from the config. Default value will be used instead." is pretty consistent as well. "Option coin_mint.canMelt was missing from the config. Default value will be used instead." is also visible, even though the CanMelt was set to true.

### To Reproduce

1. Go to config file
2. Change from .llconfig to .toml
3. Set CanMelt = True
4. Save, reload game.

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/user-attachments/files/17090697/latest.log)

**Comment by Lightman314** [comment]
The config files added by my mod are indeed `.lcconfig` files, and should remain that way to function properly. Any attempts to change the file extension of a config file will result in the renamed file not being read as it is no longer the file that the game is looking for. Thus, given what you have said, I can only assume that everything is working as intended and that you are merely confused.

**Comment by GroovieSmoothie** [comment]
I don't quite understand, I did rename it back to .lcconfig but the issue is, I turned on Melt and I can't melt coins back into ingots.

I also can't add the file into here for whatever reason

**Comment by Lightman314** [comment]
Rename it to a .txt and it should let you upload it.

**Comment by GroovieSmoothie** [comment]
[lightmanscurrency-server.txt](https://github.com/user-attachments/files/17090785/lightmanscurrency-server.txt)

**Comment by Lightman314** [comment]
I think whatever text editor was editing this changed the blank space from a normal spacebar space to full on tabs, which is a different character in the code that my config code is not expecting and doesn't automatically ignore properly.

**Comment by GroovieSmoothie** [comment]
Something else I also noticed is Tetra and the Money Mending enchantment doesn't work! But That can be dealt with later.

**Comment by Lightman314** [comment]
Finally got back from my trip, downloaded and re-named your config file back to a `*.lcconfig` file and replaced my existing config file with it, and it loaded it no problem.

Are you 100% certain that you are renaming it to a `*.lcconfig` file (starting with LC)? Cause I've noticed that in your initial issue report you were saying it was a `*.llconfig` file (starting with LL), which is *not* the correct file extension and renaming it to said file extension would cause the issue you are reporting.

**Comment by GroovieSmoothie** [comment]
It could have been a mis-write, because after kerfuffling with it for a little it began working.

Another thing I mentioned yesterday, Money Mending DOESN'T work on tetra parts! Any reason why that could be?

**Comment by Lightman314** [comment]
I have no clue because that *is* somethimg that has been consistently working for quite a while on my friends server I play on, and we've never encountered any issues with MM and tetra tools.

I should note that like all other enchantments, you still can't apply the enchantments on the tetra items in an anvil, but can only do so from the tetra workbench.
