### ISSUE TITLE
BUG: server crash on newest version

### ISSUE THREAD

**Issue by ZEROX7** [Lightman314/LightmansCurrency#25]
Minecraft Version: 1.18.1
Forge Version: 38.0.45
Lightman's Currency Version: 1.18-1.0.2.5
server log no crash log made
[latest.log](https://github.com/Lightman314/LightmansCurrency/files/7919232/latest.log)

**Comment by Lightman314** [comment]
Friggin apache... I'll have it fixed shortly...

**Comment by ZEROX7** [comment]
no worry i love your mod unfortunally nobody know it maybe you need to join forgecraft XD

**Comment by Lightman314** [comment]
I've deleted the broken version, and re-uploaded it, so you should be good to go.

**Comment by ZEROX7** [comment]
i can confirm that thx
