### ISSUE TITLE
BUG: When a fluid or energy capacity upgrade in LCtech is applied to the trader, attempting to input or output to the machine will cause the game to crash.

### ISSUE THREAD

**Issue by SSWTLZZ** [Lightman314/LightmansCurrency#252]
### Minecraft Version

1.20.1

### Forge Version

47.3.10

### Lightman's Currency Version

2.2.3.3

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

LC Tech 0.2.1.11

### Describe the bug

When a fluid or energy capacity upgrade is applied, attempting to input or output to the machine will cause the game to crash.

### To Reproduce

1.place the energy or fluid trader
2.apply the capacity upgrade
3.do some io operations
4.game crashed

### Screenshots/Logs/Crash Reports

[crash-2024-10-09_21.30.47-client.txt](https://github.com/user-attachments/files/17309243/crash-2024-10-09_21.30.47-client.txt)
[latest.log](https://github.com/user-attachments/files/17309244/latest.log)

**Comment by Lightman314** [comment]
This has been fixed in LC Tech v0.2.1.11a. Please update to this version.
