### ISSUE TITLE
Feature Request: Add crafting recipes to JEI

### ISSUE THREAD

**Issue by LunarN0v4** [Lightman314/LightmansCurrency#253]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like for all mod recipes (such as making coins) to be added to JEI.

**Describe alternatives you've considered**
There appears to not be any clear alternatives.

**Additional context**
Not available.

**Comment by Lightman314** [comment]
All of my recipes (including the coint mint & Ticket Station) are included and viewable in JEI already. Cannot add as it is already present.

**Comment by LunarN0v4** [comment]
> All of my recipes (including those for the Coint Mint & Ticket Station machines) are included and viewable in JEI already. Cannot add as it is already present.
> 
> Source: https://github.com/Lightman314/LightmansCurrency/tree/LC-1.20.1/src/main/java/io/github/lightman314/lightmanscurrency/integration/jeiplugin

doesnt seem so...
![image](https://github.com/user-attachments/assets/6d3375d0-87aa-49e6-b5a8-10c9e7382a68)

**Comment by Lightman314** [comment]
Then please make an issue report with the relevant version numbers and logs so that I can look into this issue properly.
