### ISSUE TITLE
BUG: Wallets are connected with each other

### ISSUE THREAD

**Issue by PhonedLand** [Lightman314/LightmansCurrency#255]
### Minecraft Version

1.20.1

### Forge Version

47.3.7

### Lightman's Currency Version

1.20.1-2.2.3.4

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

Hi! I'm using Lightmans Currency for my server and after the last update i noticed that all wallets on the server change their content to be the same as that of an other player as soon as you approach them. This problem apperars even if you don't have a wallet equipped, in that case it just spawns in your inventory. It also doesen't help to reinstall the mod and the logs of the sever also don't report a problem.
I hope that this description was helpful and please excuse if my wording is a little bad, english is not my first language.
Have a nice day =)

### To Reproduce

1. [Player 1] gets near [Player 2]
2. The wallet of [Player 1] and [Player 2] change to the same contents
3. [Player 1] deletes wallet
4. [Player 2] loses wallet too

### Screenshots/Logs/Crash Reports

[2024-10-10-1.log.gz](https://github.com/user-attachments/files/17350802/2024-10-10-1.log.gz)

**Comment by Lightman314** [comment]
Fixed in v2.2.3.4a. Thank you for reporting :)

(For the record this *should* only happen when two players both in creative mode are within the same area, so this shouldn't have effected a normal player)
