### ISSUE TITLE
BUG: Chocolate Coin Blocks have no assigned tool or loot table

### ISSUE THREAD

**Issue by vizthex123** [Lightman314/LightmansCurrency#256]
### Minecraft Version

1.19.2

### Forge Version

43.4.4

### Lightman's Currency Version

2.2.1.3f

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

I noticed that allowing them to fall onto an ME Annihilation Plane makes them drop loot.

### Describe the bug

The Chocolate Coin Blocks and Piles don't drop anything when mined, nor do they have mining tags - however, the regular coin versions do have drops & tags.

### To Reproduce

1. Place down any Chocolate Coin Block or Pile
2. With Jade installed, notice how it has no tool (or check the tags)

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/user-attachments/files/17351879/latest.log)

**Comment by Lightman314** [comment]
Fixed for 1.19.2 in v2.2.1.3g.

Missing tool tags will be fixed for 1.20.1 & 1.21 in the next update, but they do have the loot tables being generated properly, so that was an issue unique to 1.19.2

**Comment by vizthex123** [comment]
alright. Thanks for fixing it.

**Comment by Lightman314** [comment]
Missing tool tags for 1.20.1 & 1.21 have been added in v2.2.3.5. Closing this issue as it is now resolved for all relevant versions.

**Comment by vizthex123** [comment]
noice, thanks again for fixing it.
