### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by ChaosDogG** [Lightman314/LightmansCurrency#258]
### Minecraft Version

1.21

### Forge Version

21.1.72

### Lightman's Currency Version

1.21-2.2.3.5a

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

Mob Grinding Utils 1.1.6+mc1.21.1
Modular Routers 13.0.3

### Describe the bug

Whenever i turn off and back on the fake player farming method, the game decides to crash saying the damage type is invalid

### To Reproduce

1. Turn off fake player farming
2. Run game
3. Turn off game and back on fake player farming
4. Turn on game, start farm of choice, and watch the world fall into flames

### Screenshots/Logs/Crash Reports

[crash-2024-10-22_14.58.31-server.txt](https://github.com/user-attachments/files/17484215/crash-2024-10-22_14.58.31-server.txt)
[crash-2024-10-22_19.15.33-server.txt](https://github.com/user-attachments/files/17484217/crash-2024-10-22_19.15.33-server.txt)

**Comment by Lightman314** [comment]
Should be fixed in v2.2.3.5b :)

**Comment by ChaosDogG** [comment]
Awesome!
