### ISSUE TITLE
BUG: Crashing during / slightly after new world creation

### ISSUE THREAD

**Issue by ModifiedMC** [Lightman314/LightmansCurrency#259]
### Minecraft Version

1.20.1

### Forge Version

47.3.11

### Lightman's Currency Version

LC 2.2.3.5b

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

Crash report mentions cobblemon (v1.5.2), but it often comes up as a false positive

### Describe the bug

1. Create new world
2. Game crash

### To Reproduce

1. Create new world
2. Game crash

### Screenshots/Logs/Crash Reports

[crash-2024-10-31_11.52.17-server.txt](https://github.com/user-attachments/files/17590983/crash-2024-10-31_11.52.17-server.txt)

**Comment by Lightman314** [comment]
This is very odd, as the only reason it should be unable to get the Team data during a server tick is if the server cannot be found (which obviously should never be true during a server tick as it's kinda implied that the server exists at that point), or if the overworld isn't loaded, which also should never be true as the overworld should *always* be loaded at all times...

I can put in a workaround for safety/compatibility, but there's gotta be another mod that modifying vanilla behavior and keeping the overworld from being loaded before the first server tick or something along those lines...

**Comment by Lightman314** [comment]
null check added in v2.2.4.0
