### ISSUE TITLE
Translation: Simplified Chinese简体中文

### ISSUE THREAD

**Issue by AnsonGames** [Lightman314/LightmansCurrency#265]
### Language Name

Simplified Chinese简体中文

### Accredation

AnsonIsTheBest

### Language File

[zh_cn.txt](https://github.com/user-attachments/files/17807434/zh_cn.txt)

**Comment by AnsonGames** [comment]
wait theres sth wrong wait a min

**Comment by AnsonGames** [comment]
[zh_cn.json](https://github.com/user-attachments/files/17807489/zh_cn.json)
This is the right one

**Comment by Lightman314** [comment]
Translation added in v2.2.4.0
