### ISSUE TITLE
BUG: Where is the Team menu?

### ISSUE THREAD

**Issue by PhonedLand** [Lightman314/LightmansCurrency#268]
### Minecraft Version

1.20.1

### Forge/NeoForge Version

Forge 47.3.7

### Lightman's Currency Version

1.20.1-2.2.4.0b

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

-

### Describe the bug

The team menu is missing and nowhere to be found. I already searched in the inventory where it was before, i also tried searching in the ATMs but also didn't find anything there.

### To Reproduce

No special behavior, just buttons missing without any trace.

### Screenshots/Logs/Crash Reports (FILES ONLY)

![2024-11-23_11 21 48](https://github.com/user-attachments/assets/1f338f55-2ec2-4ae4-a3f8-eb80678d526a)

**Comment by Lightman314** [comment]
Fixed in v2.2.4.0c 
Thank you for reporting :)
