### ISSUE TITLE
BUG: trader menu overlapping

### ISSUE THREAD

**Issue by Fabian2611** [Lightman314/LightmansCurrency#269]
### Minecraft Version

1.20.1

### Forge/NeoForge Version

47.3.7

### Lightman's Currency Version

2.2.4.0b

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Other relevant Mods

None.

### Describe the bug

The elements in the Card Stand trade setting view are overlapping each other.

### To Reproduce

1. Place a Card Display
2. Right click it
3. Press "Open Trader Storage"
4. Click the Item "Click to set Item"

### Screenshots/Logs/Crash Reports (FILES ONLY)

![image](https://github.com/user-attachments/assets/e2573559-cf89-45bb-9f2c-95a934daad95)

**Comment by Lightman314** [comment]
Same issue as #268, just different symptoms

Either way, this is fixed in v2.2.4.0c
