### ISSUE TITLE
New Features?

### ISSUE THREAD

**Issue by ZEROX7** [Lightman314/LightmansCurrency#27]
1. a way to give player money on login time based like if login every day they get some money
2. a chunkloader that works with money?

**Comment by Lightman314** [comment]
1- Should be doable with other mods such as [this one](https://www.curseforge.com/minecraft/mc-mods/loyalty-rewards).

2- A chunkloader would probably be beyond the scope of Lightman's Currency, seems like more of an addon thing. That said, it would be interesting to add this to LCTech, so I'll leave this ticket open while I mull the idea over.

**Comment by ZEROX7** [comment]
go another idea a block tats like a energy taxometer thats only you can set fe rates and price for it per/hour for example

**Comment by Lightman314** [comment]
I am planning to add an energy trader to LCTech, so it's probably not impossible to allow wireless power draining from the universal variant of it. I'll probably start work on adding the energy trader to LCTech sometime next week, although it may take a while, so no promises.

**Comment by ZEROX7** [comment]
sry but just got another idea would id be possible to make the wallet placeable to act like a automated way to store coins into the bank account? got a system wehre i automated gold coins trough a infinite supply but i still have to insert them manually or maybe make it so that you can place a atm and make it insert coins to a selected account?

**Comment by Lightman314** [comment]
And interesting idea, but I probably shouldn't be making it easier to automate coin generation which is part of the reason I decided not to add the option for the netherite wallets auto-collect to deposit directly into your bank account. Adding something like this would be a great way to get inflation like there's no tomorrow. Having a dropper or dispenser spit the coins at you should be more than enough for any reasonable coin grinding need, as a netherite wallet can hold over 2 million gold coins, so unless you're going afk for days at a time your wallet should be able to hold at least as much as you can reasonably automate.

Making a machine to automatically convert coins, however, does seems like an interesting idea, cause then you can at least compress the coins into netherite coins, and then use another mods automated crafting to further compress them into netherite coin piles & blocks, but once again I'll probably leave those machines to LC Tech should I eventually decide to make them.

**Comment by Lightman314** [comment]
As there's nothing discussed here that I'm planning on implementing any time soon (the chunk loader is still in the back of my mind, but if that happens it'll be part of a land claiming addon instead of an LC feature), I'm going to go ahead and close this feature request.
