### ISSUE TITLE
BUG: Paygate crash/Forge 1.20.1

### ISSUE THREAD

**Issue by norfaremc** [Lightman314/LightmansCurrency#271]
### Minecraft Version

1.20.1

### Forge/NeoForge Version

47.3.7

### Lightman's Currency Version

2.2.4.0c

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

Hello! I'm experiencing a bug related to the paygate block. Tested 5 times, of the 5 times only on the fourth time did it produce a crash report, unsure as to why. Crashed me to desktop each time. GUI rendering issue. 

### To Reproduce

Placed paygate, opened paygate GUI, tried to click on one of the tabs on the left, crashed.

### Screenshots/Logs/Crash Reports (FILES ONLY)

[crash-2024-12-02_21.24.07-client.txt](https://github.com/user-attachments/files/17987881/crash-2024-12-02_21.24.07-client.txt)

**Comment by VirtualGaming1** [comment]
This is not just with Paygate

Minecraft Version
1.20.1

Forge/NeoForge Version
FORGE 47.3.12

Lightman's Currency Version
2.2.4.0c

Crashlog
[crash-2024-12-08_05.23.50-client.txt](https://github.com/user-attachments/files/18051844/crash-2024-12-08_05.23.50-client.txt)

**Comment by Lightman314** [comment]
Should be fixed in v2.2.4.1
