### ISSUE TITLE
BUG: Crash when clicking every place of the page of the trade interface

### ISSUE THREAD

**Issue by SSWTLZZ** [Lightman314/LightmansCurrency#272]
### Minecraft Version

1.20.1

### Forge/NeoForge Version

47.3.10

### Lightman's Currency Version

v2.2.4.1

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

when i clicked the button then game crashed

### To Reproduce

1.place an trade interface and open it
2.click any place of the page
3.game crashed

### Screenshots/Logs/Crash Reports (FILES ONLY)

[crash-2024-12-09_18.09.13-client.txt](https://github.com/user-attachments/files/18059726/crash-2024-12-09_18.09.13-client.txt)

**Comment by Lightman314** [comment]
Fixed in v2.2.4.1a. Thank you for reporting :)
