### ISSUE TITLE
[Feature Request] A trading machine type for tickets

### ISSUE THREAD

**Issue by JadianRadiator** [Lightman314/LightmansCurrency#3]
I would like to request a type of trading machine meant for selling tickets.

**Comment by Lightman314** [comment]
All of the existing trading machines are capable of selling tickets. Are you requesting 1-trade trading machine that is only capable of selling tickets (similar to how the armor display trader can only sell armor)?

**Comment by JadianRadiator** [comment]
> Edit: I'm thinking of perhaps creating a trader type that similar to normal traders, except you define the ticket your selling via the master ticket, and all that you need in storage is a ticket material (paper, old tickets, etc) and it'll "print" new tickets for the customers as they are purchased (kinda fusing the ticket machine & an item trader into one machine basically)

That sound's like a great way to do it.
I'd say it was better then how I was thinking...
except I didn't think of how to do it.

**Comment by Lightman314** [comment]
Feature implemented. It will be included on the next build for 1.16.
