### ISSUE TITLE
BUG: Mod wont load.

### ISSUE THREAD

**Issue by GoldHeartTheOne** [Lightman314/LightmansCurrency#31]
Minecraft Version: 1.18.1
Forge Version: 39.0.66
Lightman's Currency Version: 1.0.3.0 & 1.0.3.1

**Describe the bug**
minecraft crashed on startup and says failed to load mod.

**To Reproduce**
1. launch minecraft
2. game crash.

Crash Report: https://drive.google.com/file/d/1aP4vmfNqmQoomZNiUQgsMaOOObpOXiZi/view?usp=sharing
logs: https://drive.google.com/file/d/1lVdBvZx2T6TdaW3ogEIknld069fPclJG/view?usp=sharing

**Comment by Lightman314** [comment]
I am unable to replicate the issue on both server and client, even with the exact same forge version, and I've double-checked that the class in indeed present in the jar file. My best guess is that something went wrong with your forge installation and it isn't reading the mod file correctly, and/or the mod file somehow got corrupted in the download/transfer (I did download and test the file from Curseforge, so I know it didn't get corrupted during upload), so all I can really suggest is re-installing forge or getting a fresh download of my mod from Curseforge.

**Comment by GoldHeartTheOne** [comment]
a fresh install worked, thanks!
