### ISSUE TITLE
client crash wehn accessing fluid tab large

### ISSUE THREAD

**Issue by ZEROX7** [Lightman314/LightmansCurrency#32]
Minecraft Version: 1.18.1
Forge Version: 39.0.59
Lightman's Currency Version: 1.0.3.1
Other Relevant Mods & Version (LC Tech, etc.): 0.0.1.0
Connection Type (Single-player, server/client, LAN world): server

server doesnt crash just clien
[crash-2022-02-06_13.20.22-client.txt](https://github.com/Lightman314/LightmansCurrency/files/8010140/crash-2022-02-06_13.20.22-client.txt)
t

**Comment by Lightman314** [comment]
The latest version of Lightman's Currency is not compatible with LC Tech (as was somewhat noted in the changelog for v1.0.3.0, but wasn't really elaborated on so my bad there). An LC Tech will update within the next few days to make it compatible with the latest version of Lightman's Currency.

**Comment by Lightman314** [comment]
Should be fixed in v0.0.1.1, as it has updated it's compatibility with Lightman's Currency v1.0.3.1
