### ISSUE TITLE
BUG: {Duplicating Glitch}

### ISSUE THREAD

**Issue by ZeusXenios** [Lightman314/LightmansCurrency#33]
Minecraft Version: 
Forge Version: 
Lightman's Currency Version: 
Other Relevant Mods & Version (LC Tech, etc.): 
Connection Type (Single-player, server/client, LAN world): 

**Describe the bug**
Running a sever with this mod and  Inventory Profiles Next / https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next

They have found a glitch in the wallet. Where they can replicate the coins over and over and duplicate them using the auto sort feature with this system.

**To Reproduce**
1. Open wallet menu place coins in 3rd slot of diamond wallet
2. Click on sort in top right
3. Pops coins in hand to place in inventory while keeping.
4. Need option to disable wallets would help resolve this quickly

**Expected behavior**
Push coins to the left and not duplicate

**Screenshots/Logs/Crash Reports**
Shut server down as soon as this was brought to my attention. No screen shots available. 

**Additional context**
If an option could be put in for wallet disable would be great.

**Comment by Lightman314** [comment]
Fixed in v1.0.3.2. Have a good day 😄

**Comment by ZeusXenios** [comment]
Man you work fast!! I just now was reading all your replies. Great work on these mods man! This stuff is amazing work.

**Comment by ZeusXenios** [comment]
Apologies on the gap of information on the version and it is 1.18. I was in a rush and being my first bug report was sure how to fill one out in the first place. Thanks again
