### ISSUE TITLE
Feature Request: add paper money through compatibility with the city modernities mod

### ISSUE THREAD

**Issue by NixityNull** [Lightman314/LightmansCurrency#35]
could you add compatibility with this mod: https://www.curseforge.com/minecraft/mc-mods/city-modernities ?

I mean, they add paper money and you add coins, both can be stacked, and both are very well textured. I think they would work well together!

**Comment by Lightman314** [comment]
I do eventually plan on adding the ability for server owners to customize & register additional coins, however that will be a fairly complicated task that will require a complete overhaul of the coin system so do expect it to happen any time soon.

**Comment by Lightman314** [comment]
New coin chains can now be registered using the new MasterCoinList.json config added in v1.0.5.0. This should be more than enough to be able to make these two mods compatible.
