### ISSUE TITLE
[Feature Request] Blocks models

### ISSUE THREAD

**Issue by faelBrunnoS** [Lightman314/LightmansCurrency#37]
**New Models**
I am developing some models for your mod for personal use.
See below the template I created for the Ticket Kiosk:
![kiosk](https://user-images.githubusercontent.com/83606488/156938803-a9251733-12e5-4e4e-9b81-3acaba9c1f09.gif)

I haven't completed the texture yet, so it's not pretty yet!
But if you like the idea, I'll send you the models and textures for you to do whatever you want with them!
Otherwise, I'll keep it for personal use!

I'm still new to Blockbench, so I might take a while!

**Comment by Lightman314** [comment]
Sorry about the late response, I've been kinda busy lately. That said, that ticket kiosk model looks lovely and I'd love to include that as the new ticket kiosk model :)

**Comment by faelBrunnoS** [comment]
Good then!
When I'm done I'll send it to you!

But I'm just having one problem.
If you can help me with this I will be grateful.

I created the templates, but I saw that your templates that are more than 1 block high have separate .json files for each block.

I can't save models like this!  How did you do it?  My models always save 1 .json file for the 2 blocks.

**Comment by Lightman314** [comment]
I always just manually made 2 extra copies once I was done with the full block and then manually edited the top/bottom copy to cut the model in half (manually remove anything from the opposite half of the model, etc.). If you don't want to do that though (or can't figure out how), I can take care of that on my end so don't worry too much about that.

**Comment by faelBrunnoS** [comment]
Okay!
I'll leave that job to you then.

**Comment by Lightman314** [comment]
The ticket kiosk has been added, so I'm going to close the ticket for now. You can get ahold of me in my pm's if you make any new models.

**Comment by faelBrunnoS** [comment]
It's OK!
It's almost ready, just need to draw the textures!
But I'm kind of short on time right now, so it might take about a week to get ready!
