### ISSUE TITLE
[Help] Transfer to a player

### ISSUE THREAD

**Issue by faelBrunnoS** [Lightman314/LightmansCurrency#39]
How do I transfer to another player?
I put it as it is in the image below, but the button doesn't activate so I can press it.

![image](https://user-images.githubusercontent.com/83606488/157479338-60e5e933-43fc-4505-9cb8-0178220e4d8f.png)

Both players have the ATM and are online. (The Luduaver character is in the screenshot)
It works when transferring to a team.

**Comment by Lightman314** [comment]
I believe I know what's happening here, (friggin single-player having access to server-side functionality during testing is coming to haunt me again unfortunately). I'll post a quick fix to fix this issue.

**Comment by Lightman314** [comment]
Fixed in v1.0.5.3. Should now work as expected, as well as the new added feature of giving feedback on the results of the transfer ("Target account does not exist.", "Transferred X to Steve's Bank Account", etc.).
