### ISSUE TITLE
[Feature Request] Make the ticket machine hold its inventory when closed.

### ISSUE THREAD

**Issue by JadianRadiator** [Lightman314/LightmansCurrency#4]
Ticket Machine doesn't hold its inventory.
When you close its gui, all of the items you had in it get dropped either to the ground or into your inventory.
Such as how the inventory of the vanilla crafting table gets dropped when you close it.
Please update the ticket machine to allow it to hold its inventory while not in direct use.

**Comment by Lightman314** [comment]
I'm probably gonna leave the output slot auto-ejecting when you close it, but it'll now store the master ticket & paper/materials inside.

**Comment by Lightman314** [comment]
Feature implemented. It will be included on the next build for 1.16.
