### ISSUE TITLE
Feature Request: Allow purchases from ATM stored coins

### ISSUE THREAD

**Issue by K4N0** [Lightman314/LightmansCurrency#40]
**Is your feature request related to a problem? 
Problem: Kids don't remember to save some coin in the ATM.
I'd like a safe place to keep my coins since the modpack I created, you tend to die a lot.
Players continue to drop their wallet and aren't able to get it back.
Players also tend to not want to keep their coins in the ATM since you can't make purchases.
This request is mostly for the kids that don't understand financial responsibility.

Modpack: https://www.curseforge.com/minecraft/modpacks/cataclysm-zombie-apocalypse
**Describe the solution you'd like**
A server config option to allow purchases to be made from the ATM bank account money. OR
A server config option so that players wallets don't drop upon death.

**Describe alternatives you've considered**
keep inventory is just not an option.
A server config option so that players wallets don't drop upon death.

**Additional context**
Money is tight in my modpack because of the necessary expensive purchases you need to make like buying hearts, so keeping some money in the ATM for safe keeping isn't a thing since you have to keep pulling it out every time you want to make a purchase. 
However, if you lose the little money you had, you are basically in a very tough position since you are being overrun by zombies and you need at least a gun and some bullets which I've made cheap for purchase.

**Comment by Lightman314** [comment]
You stated that keep inventory is not an option, but have you tried enabling the keepWallet gamerule? That should solve your issue as it will prevent wallets from being dropped on death.

**Comment by K4N0** [comment]
I didn't realize that was a thing. Apologies and Thank You.
