### ISSUE TITLE
Feature Request: Ability to purchase more than 3 stacks

### ISSUE THREAD

**Issue by K4N0** [Lightman314/LightmansCurrency#44]
**Is your feature request related to a problem? Please describe.**
My problem is that I can only purchase 3 stacks of an item before I have to move them into my inventory and then buy 3 more. 
At times I need to buy an inventory worth of wood, but I have to keep the buying 3 at a time and move them.

**Describe the solution you'd like**
It would be nice If after the 3 slots were full from purchasing items it would then begin to fill up your inventory. 
Or for the items to just go directly into your inventory and drop on the floor if the inventory is full.

**Describe alternatives you've considered**
Potentially an inventory worth of space to purchase into vs the 3 slots.

**Additional context**

**Comment by Lightman314** [comment]
The 3 item slots have been removed as of version v1.1.0.0, and item traders will now interact directly with the players inventory. Please note that you will need to wait for an LC Tech compatibility update if you are also using LC Tech.
