### ISSUE TITLE
BUG: Mod has unintentional hard dependency on the Discord integration mod

### ISSUE THREAD

**Issue by brisingraerowing** [Lightman314/LightmansCurrency#45]
Minecraft Version (REQUIRED):  1.16.5
Forge Version (REQUIRED): 36.2.31
Lightman's Currency Version (REQUIRED): 1.0.5.6
Other Relevant Mods & Version (LC Tech, etc.): 
Connection Type (Single-player, server/client, LAN world): Crash on startup

**Describe the bug**
Game crashes with a NoClassDefFoundError on startup

**To Reproduce**
1. Launch game with LC installed (and not the Discord integration mod)
2. Crash within a few seconds

**Expected behavior**
Game launches and loads to main menu.

**Screenshots/Logs/Crash Reports**
[Crash Log](https://gist.github.com/brisingraerowing/ca9394353ffb950cabbc283dcf84f1f3)

**Additional context**
N/A

**Comment by Lightman314** [comment]
Ah, I see the issue. Should be an easy enough fix fortunately, I just accidentally made the CurrencyMessages class an event subscriber which causes forge to load the static variables even though Lightman's Discord isn't loaded.  Should be fixed shortly.

**Comment by brisingraerowing** [comment]
Sounds good. Also, this is a awesome mod. I only play singleplayer, so I just use it for decoration in my builds, but I can see the potential for multiplayer use.

**Comment by Lightman314** [comment]
Should be fixed in v1.0.5.6a.
