### ISSUE TITLE
BUG: {insert description here}

### ISSUE THREAD

**Issue by VirtualGaming1** [Lightman314/LightmansCurrency#46]
Minecraft Version (REQUIRED): 1.18.1
Forge Version (REQUIRED): 39.1.2
Lightman's Currency Version (REQUIRED): 1.1.1.1 happened on 1.0.0.0 (Beta)
Other Relevant Mods & Version (LC Tech, etc.): LC Tech 0.0.41
Connection Type (Single-player, server/client, LAN world): dedicated server

**Describe the bug**
well. one of my trader some how fully reset and I am unable to remove. because I have 2 traders and then the next day when i got on my server (public server) and for some reason the 1 trader (just the 1) got fully reset (items and owner, everything with that block)
I tired to go in creative mod and I am the owner of the server as well and i can not get rid of the block at all.

**To Reproduce**
I have nothing to reproduce at all. this is just complete RANDOM

**Expected behavior**
not sure just keep it all of the data in the block.

**Screenshots/Logs/Crash Reports**
dont have any because I have no idea when this could happen.

**Additional context**
Non at this time

**Comment by VirtualGaming1** [comment]
just wonder how if there is any work around as an op/admin/owner? If not, I would suggest that Op/Admin/Owner can remove/edit the trader just in case anyone else have an issue like this again.

**Comment by GoliathX211** [comment]
There should be the /lcadmin mode that can be used to remove a trader but I am not all too sure on that part because it is a bit out of my experience. I hope you can get this resolved, there should already be things in place to sort out the issue of removing the trader and I hope this helps.

**Comment by VirtualGaming1** [comment]
ok I will try that and will let you know

**Comment by VirtualGaming1** [comment]
that work but that is still strange how just that one block got reset. I will close this now.

**Comment by Lightman314** [comment]
Glad this got resolved, although I am also curious as to how that single trader got reset. Perhaps the world got corrupted somehow, cause I've had lots of issues with some MC server's I'm helping moderate that had lots of world corruption issues...

**Comment by VirtualGaming1** [comment]
if you want to check mine out it is in virtualgaming modpack (https://www.curseforge.com/minecraft/modpacks/virtualgaming-modpack) and there will be a button to connect to the server on the main menu. If you want
