### ISSUE TITLE
BUG: Server crashes after trying to interact/break (Item trader interface terminal)

### ISSUE THREAD

**Issue by Paolo9821** [Lightman314/LightmansCurrency#47]
Minecraft Version (REQUIRED): 1.18.2
Forge Version (REQUIRED): 40.1.0
Lightman's Currency Version (REQUIRED): lightmanscurrency-1.18.2-1.1.1.1.jar
Other Relevant Mods & Version (LC Tech, etc.): 
![Screenshot_1](https://user-images.githubusercontent.com/63623788/164994617-13e9bdb4-7f7f-41f4-9347-08c9b7e9465b.png)

Connection Type (Single-player, server/client, LAN world):  Server

**Describe the bug**
I placed the block, tried to interact with it and the server crashed.
After I restarted the server the block was still there, I tried to break it and the server crashed again.
The console reports errors regarding the mod.

**To Reproduce**
1. Place the block (Item trader interface terminal)
2. Interact with the block
3. Done, the server crashes
4. The server reports the crash log
5. The server is back online
6. You try to break the block
7. The server crashes
8. The server reports the crash log again
9. The server is back online
10. The block is still there.

**Screenshots/Logs/Crash Reports**
[crash-2022-04-24_21.53.30-server.txt](https://github.com/Lightman314/LightmansCurrency/files/8550437/crash-2022-04-24_21.53.30-server.txt)

**Comment by Lightman314** [comment]
This issue was fixed 3 hours ago in v1.1.1.1a. Please make sure that your issue has not already been fixed before reporting in the future.
