### ISSUE TITLE
BUG: {Netherite Duplication}

### ISSUE THREAD

**Issue by tmanfoo1** [Lightman314/LightmansCurrency#49]
Minecraft Version (1.18.1): 
Forge Version (39.1.0): 
Lightman's Currency Version (lightmanscurrency-1.18-1.0.5.3.jar): 
Other Relevant Mods & Version (create create-mc1.18.1_v0.4d.jar, storage drawers StorageDrawers-1.18.1-10.1.1.jar): 
Connection Type (server/client): 

**Describe the bug**
Netherite is duplicated when extracted from a smart chute

**To Reproduce**
1. create a pillar as follows:
smart chute [where you drop the netherite coin]
minting press
smart chute
storage drawer [which recieves ghost items it seems]
hopper
**Expected behavior**
2 netherite coins in the top
64 netherite ingots in the hopper at the bottom

**Screenshots/Logs/Crash Reports**
You can find your minecraft logs in the /logs folder (ideally the latest.log file if you've not launched your game again since the error happened, and/or crash report if a crash happened)

**Additional context**
as a coder it seems that what is happening is the smart chute is extracting a stack of items at a time and so the thing tries to extract a stack from the minting machine when imputed. It seems like the items are ghost items that actually cant be interacted with and would normally go away, but with the hoper extraction the items become tangable.

**Comment by Lightman314** [comment]
Update, I found the issue. It should be patched shortly. The real problem here is that create uses the results from the simulation form of the extract function instead of the non-simulated form, and my "simulation" of the coin minting was unfortunately inaccurate.

**Comment by Lightman314** [comment]
Fixed in v1.1.2.1.
