### ISSUE TITLE
Feature Request: Minecraft Comes Alive Reborn Integration/support

### ISSUE THREAD

**Issue by GeminiMarshdevil** [Lightman314/LightmansCurrency#53]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is:
Lightman's currency seems to be incompatible with Minecraft Comes Alive Reborn
https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn

**Describe the solution you'd like**
Villagers in MCAr to also be affected with the same changes as vanilla villagers.  
it would make the entire experience so much more immersive. trades, taxes, all the stuff to just wholesale replace emerald use with copper/silver/gold coinage.

**Additional context**
![image](https://user-images.githubusercontent.com/35816347/171092674-98587d45-7504-46b8-98b3-c5f0eaee0b9a.png)
![image](https://user-images.githubusercontent.com/35816347/171092786-46497703-0db1-4160-964b-cf0f7aff74ba.png)
![image](https://user-images.githubusercontent.com/35816347/171092815-f1712487-9e8f-4a3d-a6ab-dbb6e95fed61.png)

**Comment by Lightman314** [comment]
I'm not sure what you mean by "Villagers in MCAr to also be affected with the same changes as vanilla villagers." as I do not touch the vanilla villagers (aside from adding trades to the wandering trader, and the addition of the banker/cashier villagers) in any way shape or form, and if they aren't properly carrying those changes over to their villagers (as my mod adds the cashier/banker villagers with proper vanilla methods), then that's something they need to look into themselves I'm afraid.

Adding any methods to change the trades of the MCA villagers would likely need to be done on their end as well, either by them adding some method of customizing their villagers trades, or what have you. I would recommend making this suggestion/request to them, as I'm not in any way familiar with MCA and I don't have enough free time to look through their code and figure out how to modify their villagers trades (if it's even doable from an external mod).

**Comment by GeminiMarshdevil** [comment]
gotcha, cool, sorry to have bothered you ^^; 
you're a legend for replying and being so cordial! thank you for your time!
