### ISSUE TITLE
BUG: Blocks facing different directions

### ISSUE THREAD

**Issue by Bluemagelord** [Lightman314/LightmansCurrency#55]
Minecraft Version (REQUIRED): 1.18.2
Forge Version (REQUIRED): 40.1.25
Lightman's Currency Version (REQUIRED): lightmanscurrency-1.18.2-1.1.5.1.jar (we tried everything back to 
lightmanscurrency-1.18.2-1.1.4.3a.jar) 
Other Relevant Mods & Version (LC Tech, etc.): 
Connection Type (Single-player, server/client, LAN world): Server

**Describe the bug**
So we installed this mod to our server. When we tried to place items like the spruce shelf, the items were always facing a different direction than intended. If you faced south, the block would face north, If you faced east, it would face west, etc. Also, sometimes if you placed the block it would visually change the block that was placed. So a spruce shelf became a large vending machine or a birch shelf, etc.

So not only could we not see what was on the shelf to be sold/purchased, several times we couldn't interact with the block (because of the switch from the shelf to the vending machine). 

**To Reproduce**
So we updated from 1.1.5.0 to 1.1.5.1 to see if that was it. 
Then we went back to 1.1.4.3a to see if an earlier version would help. 

Neither of these efforts fixed the problem. 

**Expected behavior**
We would like to use your mod as it handles several issues we need for our server's economy. 

**Screenshots/Logs/Crash Reports**
Screenshot showing the sideways birch shelves and vending machines [https://imgur.com/6Ub0QUa]

**Additional context**

**Comment by Bluemagelord** [comment]
I should also note: this bug wasn't just that the blocks were facing the wrong direction. Once placed, you couldn't interact with the blocks. So when you placed a spruce shelf (which visually became a large vending machine) you couldn't interact with it, even if you found the "front" of the block.

**Comment by Bluemagelord** [comment]
Oddly enough, this weird texture problem has caused other mods (Ars Nouveau) to show some texture issues now. 

[https://imgur.com/NrFoDs9] The blocks shouldn't appear to be surrounded by water.

**Comment by Lightman314** [comment]
I am unable to replicate this issue, and it seems to me like there is an issue with your forge installation preventing it from running the Block.setPlacedBy & Block.getStateForPlacement functions, both of which are used by my mod (the first to set the player who placed the block as the traders owner, and the second to set the blocks rotation based on the players current horizontal facing). I would try re-installing forge, as there is clearly some corrupted minecraft shenanigans, which is probably also why the Ars Nouveau blocks are being spawned in as waterlogged (as the default boolean blockstate value will always be true unless overridden by the block in functions that are obviously not working properly in your installation).

**Comment by Lightman314** [comment]
Closing due to lack of response, and my previous assessment that it is not an issue caused by my mod, merely an issue caused by an outside source that happens to be affecting my mod.
