### ISSUE TITLE
BUG: ATM UI gets cut off

### ISSUE THREAD

**Issue by vizthex123** [Lightman314/LightmansCurrency#59]
Minecraft Version (REQUIRED): 1.18.2
Forge Version (REQUIRED): 40.1.41 (can't update otherwise it crashes the pack)
Lightman's Currency Version (REQUIRED): 1.1.5.2
Other Relevant Mods & Version (LC Tech, etc.): 
Connection Type (Single-player, server/client, LAN world): All

**Describe the bug**
The UI for the ATM doesn't fit on my screen

**To Reproduce**
1. Have GUI size set to auto
2. Open the ATM

**Expected behavior**
The UI would fit on my screen

**Screenshots/Logs/Crash Reports**
![image](https://user-images.githubusercontent.com/31721920/175655458-ebe9ab73-4955-4478-be18-615729d33982.png)

Don't think the log is necessary, but here it is just in case:
[latest.log](https://github.com/Lightman314/LightmansCurrency/files/8980255/latest.log)

**Additional context**

**Comment by Lightman314** [comment]
Per the Curseforge Description:
![image](https://user-images.githubusercontent.com/4554273/175656806-2557e857-c6e1-42af-b3fa-fe36fb03ba5a.png)

**Comment by vizthex123** [comment]
Perhaps you could scale down the coin selector on the top?
