### ISSUE TITLE
BUG: Tickets aren't craftable

### ISSUE THREAD

**Issue by vizthex123** [Lightman314/LightmansCurrency#61]
Minecraft Version (REQUIRED): 1.18.2
Forge Version (REQUIRED): 40.1.41 (can't update otherwise it crashes the pack)
Lightman's Currency Version (REQUIRED): 1.1.5.2
Other Relevant Mods & Version (LC Tech, etc.): 
Connection Type (Single-player, server/client, LAN world): All

**Describe the bug**
Tickets have no crafting recipe, but based on my understanding of how they work, they should have one by default. Added one myself for now, but figured I could report it while I'm here.

**To Reproduce**
1. Check the ticket recipe using JEI

**Expected behavior**
It would have a recipe

**Screenshots/Logs/Crash Reports**

**Additional context**

**Comment by Lightman314** [comment]
Tickets are made from paper, tickets, master tickets, or ticket stubs using the Ticket Machine. At best this should be a feature request to add the recipe to JEI.

**Comment by vizthex123** [comment]
You could add JEI info for it, that'd help a lot.

**Comment by Lightman314** [comment]
Unfortunately it's not that simple, as I'd need to make the ticket "recipes" into actual recipe types that get loaded in via data pack in order for it to work with JEI. It's doable, ye, but extremely annoying to do (trust me, I already had to do it once for the coin mint). Either way, that'd still be a feature request, not a bug report.

**Comment by vizthex123** [comment]
Really? I never knew adding info tabs was that annoying, cuz with CraftTweaker it's pretty easy (I'm using `mods.jei.JEI.addDescription(<item:minecraft:paper>, ["Can be used to make tickets in a Ticket Machine"]);
` in my pack, for example). Assumed it'd be so with modding.

**Comment by Lightman314** [comment]
I didn't consider doing it that way. I was thinking of actually making it show the Ticket Machine's UI, just like how the furnace/coin mint show the items in the UI. That should actually be easy enough to manage, thanks for the idea as I completely forgot that was a feature in JEI.

**Comment by vizthex123** [comment]
Yeah, having JEI Info would be a good work-around until you add full support (if you're ever able to).

And anytime, I went ahead and added it to paper & all the tickets in my modpack. Maybe do the same for the mod itself?
