### ISSUE TITLE
Feature Request: {Turn off multiple items to increase FPS}

### ISSUE THREAD

**Issue by TenseikenSlash** [Lightman314/LightmansCurrency#64]
**Is your feature request related to a problem? Please describe.**
In a new, flat, empty world I get around 1800 FPS. If I then place only 3 vending machines and pack them full with item stacks, especially for buying with lots of money inside the machine, the game will run at 20 FPS, because it has to render every single item
in the machine that is stacked behind each other.

**Describe the solution you'd like**
I would suggest only one item of each type to show inside the machine, for example like in a frame.

**Describe alternatives you've considered**
/

**Additional context**
I am using your 1.18 version, since that version is the one of my game. I would be nice if the solution could be applied to this version.
Thanks for your work, beside that issue the mod is awesome.

**Comment by Lightman314** [comment]
There is a config option in the lightmanscurrency-client.toml config file that lets you lessen to 1 item per trade (or technically 2 if it's selling two items), or just disable them entirely.

Also, please check the FAQ & wiki before making feature requests, as this is literally the first question that is answered in the FAQ provided in my mods description.

![image](https://user-images.githubusercontent.com/4554273/175833390-44da147a-9cda-4f18-ab1a-6382f718a3ba.png)
