### ISSUE TITLE
Bug: 1.19, 1.19, 1.19 none, server, can't access trader storage.

### ISSUE THREAD

**Issue by MrNotTooGood** [Lightman314/LightmansCurrency#68]
Minecraft Version (REQUIRED): 1.19
Forge Version (REQUIRED): 1.19
Lightman's Currency Version (REQUIRED): 1.19
Other Relevant Mods & Version (LC Tech, etc.): none
Connection Type (Single-player, server/client, LAN world): server

**Describe the bug**
A clear and concise description of what the bug is. Cannot access trader storage

Just will not allow me to open trader storage on anything

**Comment by Lightman314** [comment]
Has been 1 week with no response, closing the issue. Feel free to re-open the issue when you can give me the context I require to actually address your issue.
