### ISSUE TITLE
BUG: [1.19] version crashes on forge 41.0.64 and higher

### ISSUE THREAD

**Issue by Pietropil15418** [Lightman314/LightmansCurrency#71]
Minecraft Version (REQUIRED): 1.19
Forge Version (REQUIRED): 41.0.64 and higher
Lightman's Currency Version (REQUIRED): 1.19-1.1.6.3a
Other Relevant Mods & Version (LC Tech, etc.): None
Connection Type (Single-player, server/client, LAN world): Single-Player

**Describe the bug**
when using the 1.19 version of lightmans currency, the mod loads correctly on forge versions of 41.0.63 and lower, but in 41.0.64 and higher it crashes while loading

**To Reproduce**
1. try to load the mod with any version of forge that is 41.0.64 or higher
2. see the error

**Expected behavior**
the mod to load correctly on forge versions of 41.0.64 or higher

**Screenshots/Logs/Crash Reports**
You can find your minecraft logs in the /logs folder (ideally the latest.log file if you've not launched your game again since the error happened, and/or crash report if a crash happened)
[latest.log](https://github.com/Lightman314/LightmansCurrency/files/9090745/latest.log)
[crash-2022-07-12_09.49.43-fml.txt](https://github.com/Lightman314/LightmansCurrency/files/9090760/crash-2022-07-12_09.49.43-fml.txt)

**Additional context**

**Comment by Lightman314** [comment]
Makes sense, looking through the forge changelogs they made some major changes to how client-side stuff is registered, so I'll need update to that version of forge for development...
