### ISSUE TITLE
Feature Request: configure toggle to make all vanilla trades use coins

### ISSUE THREAD

**Issue by GeminiMarshdevil** [Lightman314/LightmansCurrency#72]
**Is your feature request related to a problem? Please describe.**
No Problem. just a plain old feature request.

**Describe the solution you'd like**
i'd love a config option to replace all vanilla trades with lightman's currency trades.  just wholesale swap out emerald use with emerald coin use. emerald coins instead of raw emeralds would be a killer feature and really push lightman's currency to the forefront of any modpack.

**Additional context**
i'm a modpack maker. i make modpacks for large server communities. we're desperate to find a currency mod that will hyjack the whole vanilla experience.  i understand that isn't always desirable for every modpack so i figure having it be a configure toggle choice on the modpack maker's side of things, would be the smarter option. 
in such a situation, i'de disable the minting of coins wholesale and have them be found in the loot table via mob drops/treasure chests to stimulate diverse gameplay rather than favoring "only minors" or "only farmers" or "only dungeon divers".

**Comment by Lightman314** [comment]
I can't make any promises, as I'm unsure if it's possible to remove vanilla trades, but this does sound like something that'd be fun to try and figure out how to implement it.

**Comment by Lightman314** [comment]
Added in v1.1.6.5!

**Comment by GeminiMarshdevil** [comment]
you are the absolute boss! Thank you! :heart: 
my server community is going to go nuts for this!
here is the modpack im making, the very next update will have your new edit and the world customized with the coin trades
https://www.curseforge.com/minecraft/modpacks/shaped-aion-cubes/files
