### ISSUE TITLE
BUG: lightman's trade not "fully" replaced with modded trades.

### ISSUE THREAD

**Issue by GeminiMarshdevil** [Lightman314/LightmansCurrency#74]
Minecraft Version (REQUIRED): 1.18.2
Forge Version (REQUIRED): 40.1.60
Lightman's Currency Version (REQUIRED): 1.1.6.5
Other Relevant Mods & Version (LC Tech, etc.): N/A
Connection Type (Single-player, server/client, LAN world): singleplayer, also multipleplayer

**Describe the bug**
Lightman's villager trade replacements is not a complete replacement for modded trades.  specifically Farmer's Delight trades still use emeralds

**To Reproduce**
1. install farmer's delight & lightman's currency, optionally trade-cycle for easier testing, into an instance of minecraft
2. launch the newly created instance
3. find a villager with the farming profession 
4. cycle through trades till a farmer's delight trade option appears. it will be in emeralds, not coins.

**Expected behavior**
the farmer's delight trades, and all other modded trades, to use emerald coinage from lightman's currency :heart: 

**Screenshots/Logs/Crash Reports**
![image](https://user-images.githubusercontent.com/35816347/179704763-fe8b4380-6c8f-4dc8-ae43-cd05c6d7ad03.png)

apparently the bee keeper profession is also affected
![image](https://user-images.githubusercontent.com/35816347/179735686-60129df4-f62f-4f91-a6ca-3c9752b55ce5.png)

byg is also affected
![image](https://user-images.githubusercontent.com/35816347/179747958-473b3032-61c2-44b8-a16c-c170771e1aeb.png)

**Comment by Lightman314** [comment]
Did you also enable the "changeModdedTrades" config option in addition to the "changeVanillaTrades" config?

**Comment by Lightman314** [comment]
Should be fixed in v1.1.6.5a.

**Comment by GeminiMarshdevil** [comment]
You are a Scholar and a Gentleman. :heart:
