### ISSUE TITLE
Feature Request: Config option to choose which coin type is used for villager trades.

### ISSUE THREAD

**Issue by GeminiMarshdevil** [Lightman314/LightmansCurrency#76]
**Is your feature request related to a problem? Please describe.**
No Problem! other than late game runaway economies all being based on emerald coinage.
make it so we can assign which coin type to use for villager trades. 
example: 
instead of strictly emerald coins, lets make it strictly iron coins. 

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/35816347/180277351-2b7298f8-5524-45ba-ac3c-0c438e0cf11f.png)

**Describe alternatives you've considered**
granular control of "which profession uses what coin type for trades" 
suddenly i can tell fisherman to only deal in iron
clerics to only deal in emerald
and map maker to only deal in copper (fukin Neeeerrrds)
fletcher only deals in copper (cuz sticks are not bloody worth 3 emerald coins)

**Comment by Lightman314** [comment]
I probably won't give it it's own json file, due to how simple I can make the inputs for it, but I do like the idea of adding both a "defaultTraderCoin" input and a "traderOverride" list input to the config that lets you change the coin item for each specific villager type.

**Comment by GeminiMarshdevil** [comment]
epic you are a legend of the highest caliber. :heart:

**Comment by Lightman314** [comment]
Added in v1.1.6.6. It has some helpful default values as well, moving most vanilla villagers down to iron coins, leaving only those that deal in enchantments or tools/armor at emerald coins.

**Comment by GeminiMarshdevil** [comment]
hey, sorry to bring this back up but where is the new config file for the trader's coin uses?  i've updated the mod and launched the pack registered that the update is working but i cant find the config file that contains the trader's coin uses specifically.
