### ISSUE TITLE
BUG: {java.lang.Exception: Mod Loading has failed}

### ISSUE THREAD

**Issue by jackspearee** [Lightman314/LightmansCurrency#77]
Minecraft Version (REQUIRED):  1.18.2
Forge Version (REQUIRED): 40.1.68
Lightman's Currency Version (REQUIRED): tried all of them for 1.18.2
Other Relevant Mods & Version (LC Tech, etc.): nope
Connection Type (Single-player, server/client, LAN world): Single-player

**Describe the bug**
Whenever I tried to open MC, after loading screen, there is a crash error in front of me which says;
                        Description: Mod loading error has occurred
                        java.lang.Exception: Mod Loading has failed

1. Open MC
2. Loading Screen
3. Crash

I've tried every single version of mod and also of forge, tried to open with only this mod also but nothing changed.

![image](https://user-images.githubusercontent.com/109757553/180282943-126f9535-79ac-4a9f-86c8-67f5b9315d1c.png)

Please save my soul
![unknown](https://user-images.githubusercontent.com/109757553/180283594-c21776ab-8308-4c56-82db-58e07f363bb7.png)

**Comment by Lightman314** [comment]
Please provide the crash report. I cannot help you without it.

**Comment by jackspearee** [comment]
[crash-2022-07-21_21.39.36-fml.txt](https://github.com/Lightman314/LightmansCurrency/files/9161930/crash-2022-07-21_21.39.36-fml.txt)

Here, thanks.

**Comment by Lightman314** [comment]
Should be fixed in v1.1.6.5b
