### ISSUE TITLE
Feature request abridged: location of the trader's coins config?

### ISSUE THREAD

**Issue by GeminiMarshdevil** [Lightman314/LightmansCurrency#78]
hey, sorry to bring this back up but where is the new config file for the trader's coin uses? 
i've updated the mod and launched the pack. registered that the update is working, but i cant find the config file that contains the trader's coin uses specifically.

is it hidden in one of these?
![image](https://user-images.githubusercontent.com/35816347/180642390-217faec2-24ab-4a53-a950-41caf7641fea.png)

![image](https://user-images.githubusercontent.com/35816347/180642408-b23c41e2-75bd-4d15-a4b2-47c898f69cf2.png)

**Comment by Lightman314** [comment]
![image](https://user-images.githubusercontent.com/4554273/180657525-17122709-697e-4665-a46b-fdbe38ce1f63.png)
