### ISSUE TITLE
BUG: "/kill @e[type=minecraft:armor_stand]" breaks trader notifications

### ISSUE THREAD

**Issue by HonzaVinCZ** [Lightman314/LightmansCurrency#81]
Minecraft Version (REQUIRED): 1.18.2
Forge Version (REQUIRED): 40.1.51
Lightman's Currency Version (REQUIRED): lightmanscurrency-1.18.2-1.1.6.3a
Other Relevant Mods & Version (LC Tech, etc.): lctech-1.18.2-0.0.5.9, lightmansdiscord-1.18-0.0.3.8-server
Connection Type (Single-player, server/client, LAN world): server

**Describe the bug**
If command /kill @e[type=minecraft:armor_stand] is used, it breaks all trader notifications. I could not find any way how to restore the notifications without breaking the trader. 
I used that command because there was another bug when I mined Armor Display with armor equipped and the armor stand entity stayed there. It did not disappear even after some time and several server restarts and it was not possible to damage it so that forced me to use that command.

EDIT: When that happens, except the notifications, shop works as usual.

**To Reproduce**
1. Place any trader, set trade and try buy something to see notifications
2. Type command /kill @e[type=minecraft:armor_stand]
3. Now buy again something from the same trader and notifications are not present anymore

**Expected behavior**
There should be some sort of workaround for this issue. I maybe see the point of using armor stand as messager entity but we need to at least restore that entity after it has been killed.

**Comment by Lightman314** [comment]
I have no clue how this could be happening, as armor stands have literally nothing to do with the notifications. Heck, they don't functionally do anything even for the armor displays, they're just spawned as a visual for the armor that the armor display is selling.

**Comment by HonzaVinCZ** [comment]
Well that is interesting. When I used that command, it deleted 10 entities (worth to note that there was no armor stand placed by player) and that ammount equals to ammount of traders present in my shop.
Trader used is Large Vending Machine (Black).

I'm going to test it again tomorrow if I can reproduce it and send some log and screenshots. Today I just found it but server restart happened already so there is no log.
I have another two player that had active shops when that happened, one online, second offline. I ask them as well if their shop notifications work.

**Comment by HonzaVinCZ** [comment]
> I have no clue how this could be happening, as armor stands have literally nothing to do with the notifications. Heck, they don't functionally do anything even for the armor displays, they're just spawned as a visual for the armor that the armor display is selling.
> 
> Edit: I tested it on the latest version for both 1.18.2 & 1.19, and could not replicate this issue. ![image](https://user-images.githubusercontent.com/4554273/184965152-d3d9bc11-3574-4e9d-af9c-3b9aefb523ad.png)

I have literally no idea what happened but it works again when I logged in and tested it again. This is some weird stuff happening. 
May be some client desync? But it was happening during my constant stay for about 2 hours. My previous shop notifications were gone but now they are back.

Anyway because I can't reproduce it again, feel free to close this issue, I don't want to mess your issues page with unclear issue.

**Comment by Lightman314** [comment]
To be fair, I have now noticed that the armor stand spawning issue wasn't 100% fixed now, as I did some more thorough testing and the armor displays are still spawning extra armor stands when the chunk is re-loaded, etc. But the issue with the notifications does seem to have simply been some sort of network or desync error.
