### ISSUE TITLE
Friends United Pack Expierence Feature Request

### ISSUE THREAD

**Issue by Zelioth** [Lightman314/LightmansCurrency#90]
**All Trade Machines GUI for Edit Trader's Trade Rules -** 
Currently the GUI is a bit confusing. Making it where you can open the trade rules and just see the start screen that currently shows "Sales,Blacklist, Player Trade Limit, Whitelist,Trade Limit,Discount, free samples" and when you check mark/turn on one of the features the tab for that feature will appear instead of them all just being present when disables or enabled.

**Free Samples for all Trade Machines -** 
Free samples currently operate where you turn it on in the trade rules but if a machine has multiple items you only get one free sample and all the other items in the machine don't allow you redeem free samples. (Example, Armor Display has free samples turned on and a full set of starter armor. I chose the helmet for my free samples and it wouldn't let me claim any of the rest of the armor, it went to charging.) so adding where we can maybe choose which items in the machines get free samples or just allowing the every item in the shop to give a free sample. 

**Player Trade Limit per Trader -**
Currently if you set the player trade limit in the trade rules it applies it to everything in the trader. giving us the ability when setting price to set trade limits per item would be better. Maybe turning the option on in Trade rules, then returning to the item where you set price would now have a option for trade limits, but if the Trade Rule for Trade limits is off there is no option present. 

**Create mode for traders -**
Currently if you enable creative mode for a trader it shows a RED X over the C. This to me indicates that the Creative mode is disabled but currently the RED X means that it is enabled. Changing this would make it more clear. Where as the C without X means enabled and the C with the RED X means disabled.

**Comment by Lightman314** [comment]
Should be fixed in v2.0.0.2 :)
