### ISSUE TITLE
BUG: {insert description here}

### ISSUE THREAD

**Issue by albertosaurio65** [Lightman314/LightmansCurrency#91]
Minecraft Version (REQUIRED): 1.19.2
Forge Version (REQUIRED):  1.19.2 - 43.1.28
Lightman's Currency Version (REQUIRED):  lightmanscurrency-1.19.2-2.0.0.2

**Describe the bug**
Start minecraft

![image](https://user-images.githubusercontent.com/70109413/192360092-ab5bb2da-5f9c-446b-a4e7-c7ea0e0551d6.png)

**Comment by Lightman314** [comment]
Please provide the **entire** crash report, not just the single line.

**Comment by Lightman314** [comment]
Tested with the latest version of forge, and the game launched just fine. Unable to replicate.

**Comment by albertosaurio65** [comment]
Será alguna incompatibilidad o algo puntual, tampoco probé mucho, en el log no venía ningún error, directamente después de la carga normal saltaba el crash, ya sí lo pruebo otro día y no va pues específico

**Comment by albertosaurio65** [comment]
Será alguna incompatibilidad o algo puntual, tampoco probé mucho, en el log
no venía ningún error, directamente después de la carga normal saltaba el
crash, ya sí lo pruebo otro día y no va pues específico
