### ISSUE TITLE
Feature Request: Rent Payment Purchase System

### ISSUE THREAD

**Issue by Chassx2** [Lightman314/LightmansCurrency#95]
Using the existing system for currency, We are looking to have a system where you can purchase a plot of land, home or more. 
The current system requires that you trade a item or such. With such we would need a trade block that is capable of just setting a purchase price and they can pay it. 

![2022-10-02_06 17 00](https://user-images.githubusercontent.com/56740526/193449225-0557db42-a3e3-4730-8282-fc5911c6bd92.png)

Basic functionality: 
we would need a trade block that is capable of just setting a purchase price and they can pay it.  Once paid it could do nothing, output a redstone signal or keep a log of date/time. 

Advanced Functionality 
The system could be based on a set timer so that x days/hours/seconds and the block would reset so they would have to pay again.
It could allow OPS to output a command on reset as well.

**Comment by Lightman314** [comment]
If you just need something that outputs a redstone signal, why not use the Paygate? And if you need a time so that they can only pay every X time units, just add the Player Trade Limit rule to the Paygate, as it allows you to limit them to X trades for every X period of time.
