### ISSUE TITLE
BUG: Villager trade offer modifications don't seem to work

### ISSUE THREAD

**Issue by ZEROX7** [Lightman314/LightmansCurrency#96]
Minecraft Version: 1.19.2 
Forge Version (REQUIRED): 43.1.28
Lightman's Currency Version: lightmanscurrency-1.19.2-2.0.0.2b.jar
Other Relevant Mods & Version (LC Tech, etc.): lctech-1.19.2-0.1.0.0.jar
Connection Type (Single-player, server/client, LAN world): SP

![javaw_UN1I5KkMwH](https://user-images.githubusercontent.com/12628051/193555870-9da3efe6-c1da-4911-a09d-2bcd29c6698c.png)

**Comment by Lightman314** [comment]
That's odd, as it's working as intended on my end.
![image](https://user-images.githubusercontent.com/4554273/193911890-a0f238e0-5fc9-43dd-9661-2a998a62a405.png)

**Question**: Did you fully reboot the game after making the configuration changes? Cause villager trade offers are registered at the games launch (similar to how items/blocks are registered), so any villager related changes require the game to be fully closed and rebooted for the changes to be applied.

The changes also won't take affect for any villagers that already have their trades/employment locked by carrying out a trade, although any additional trades they gain from leveling up will use the modified offers.

**Comment by ZEROX7** [comment]
wierd
