### ISSUE TITLE
Error giving me op on my server

### ISSUE THREAD

**Issue by DripTripa** [Lightman314/LightmansCurrency#99]
![image](https://user-images.githubusercontent.com/117004330/198869585-43a288e7-c728-4538-96e8-7e2d47e7d58c.png)

**Comment by DripTripa** [comment]
It only happens when I give op to take it out if it lets me enter my server, try to play with the values of the permissions on my server but only change the message, but I think it has something to do with some complement of the mod that stores me digital money then to give me op me changes name

**Comment by Lightman314** [comment]
First off, please follow the bug report template provoded. Second off, please provide the logs from both the server AND the client, as that error message is 100% unreadable.

**Comment by Lightman314** [comment]
Closing due to lack of response and a heavy doubt that my mod had *anything* to do with this.
